"""Hardcoded list of ~250 generic reasoning patterns for seed data generation."""

from __future__ import annotations

REASONING_PATTERNS: list[dict[str, str]] = [
    # =========================================================================
    # DEDUCTIVE (25)
    # =========================================================================
    {
        "name": "Modus Ponens",
        "category": "deductive",
        "description": "If P implies Q and P is true, then Q must be true. The most fundamental rule of deductive inference.",
        "when_to_use": "When you have a confirmed conditional and its antecedent is established as true.",
    },
    {
        "name": "Modus Tollens",
        "category": "deductive",
        "description": "If P implies Q and Q is false, then P must be false. Derives the negation of a premise from the negation of its consequence.",
        "when_to_use": "When you observe that an expected consequence did not occur and need to reject the premise.",
    },
    {
        "name": "Disjunctive Syllogism",
        "category": "deductive",
        "description": "If either P or Q is true and P is false, then Q must be true. Eliminates one branch of a disjunction.",
        "when_to_use": "When you can rule out one of two mutually exhaustive possibilities.",
    },
    {
        "name": "Hypothetical Syllogism",
        "category": "deductive",
        "description": "If P implies Q and Q implies R, then P implies R. Chains conditional statements together transitively.",
        "when_to_use": "When building a chain of implications to connect a premise to a distant conclusion.",
    },
    {
        "name": "Categorical Syllogism",
        "category": "deductive",
        "description": "Derives a conclusion from two premises that share a common middle term linking subject and predicate classes. Classic form: All A are B, all B are C, therefore all A are C.",
        "when_to_use": "When reasoning about class membership and subset relationships.",
    },
    {
        "name": "Constructive Dilemma",
        "category": "deductive",
        "description": "Given two conditionals and the disjunction of their antecedents, concludes the disjunction of their consequents.",
        "when_to_use": "When facing two possible starting conditions that each lead to their own outcome.",
    },
    {
        "name": "Destructive Dilemma",
        "category": "deductive",
        "description": "Given two conditionals and the negation of at least one consequent, concludes the negation of at least one antecedent.",
        "when_to_use": "When the failure of at least one expected outcome lets you reject at least one assumption.",
    },
    {
        "name": "Reductio ad Absurdum",
        "category": "deductive",
        "description": "Assumes a proposition is true and derives a contradiction, thereby proving the proposition false. A powerful technique for indirect proof.",
        "when_to_use": "When a direct proof is difficult but you can show the negation leads to contradiction.",
    },
    {
        "name": "Proof by Contradiction",
        "category": "deductive",
        "description": "Assumes the negation of the desired conclusion and derives a logical impossibility, establishing the original conclusion must hold.",
        "when_to_use": "When you want to prove something by showing its denial is impossible.",
    },
    {
        "name": "Proof by Cases",
        "category": "deductive",
        "description": "Exhaustively divides the problem into mutually exclusive cases and proves the conclusion holds in every case.",
        "when_to_use": "When a proposition can be broken into a finite number of scenarios that collectively cover all possibilities.",
    },
    {
        "name": "Universal Instantiation",
        "category": "deductive",
        "description": "From a universal statement about all members of a class, infers the same property for any specific individual in that class.",
        "when_to_use": "When applying a general rule or law to a specific instance.",
    },
    {
        "name": "Existential Generalization",
        "category": "deductive",
        "description": "From a known instance with a property, infers that there exists at least one thing with that property.",
        "when_to_use": "When you have a concrete example and need to establish that something with that property exists.",
    },
    {
        "name": "Universal Generalization",
        "category": "deductive",
        "description": "From a proof that an arbitrary member of a class has a property, concludes all members have that property.",
        "when_to_use": "When you can show a property holds for an arbitrary representative without relying on its specifics.",
    },
    {
        "name": "Biconditional Reasoning",
        "category": "deductive",
        "description": "From P if and only if Q, derives that P and Q are logically equivalent: both true or both false.",
        "when_to_use": "When two conditions are known to be necessary and sufficient for each other.",
    },
    {
        "name": "Conjunction Introduction",
        "category": "deductive",
        "description": "If both P and Q are independently established, then their conjunction P-and-Q is also established.",
        "when_to_use": "When combining two independently verified facts into a single compound assertion.",
    },
    {
        "name": "Conjunction Elimination",
        "category": "deductive",
        "description": "From a conjunction P-and-Q, either conjunct P or Q can be individually extracted as true.",
        "when_to_use": "When you need to isolate one component of a compound fact.",
    },
    {
        "name": "Contrapositive Reasoning",
        "category": "deductive",
        "description": "Recognizes that if P implies Q, then not-Q implies not-P. The contrapositive is logically equivalent to the original conditional.",
        "when_to_use": "When it is easier to reason from the absence of a consequence back to the absence of a cause.",
    },
    {
        "name": "Mathematical Induction",
        "category": "deductive",
        "description": "Proves a base case and then proves that if the statement holds for case n, it holds for n+1, establishing the statement for all natural numbers.",
        "when_to_use": "When proving a property that must hold for every element in a well-ordered sequence.",
    },
    {
        "name": "Strong Induction",
        "category": "deductive",
        "description": "Assumes the property holds for all cases up to n and uses this to prove it for n+1, providing a stronger inductive hypothesis.",
        "when_to_use": "When the inductive step requires knowledge about all preceding cases, not just the immediate predecessor.",
    },
    {
        "name": "Structural Induction",
        "category": "deductive",
        "description": "Proves a property for base structures and shows it is preserved by all construction rules, establishing it for all well-formed structures.",
        "when_to_use": "When reasoning about recursively defined structures like trees, lists, or formal expressions.",
    },
    {
        "name": "De Morgan's Reasoning",
        "category": "deductive",
        "description": "Transforms the negation of a conjunction into a disjunction of negations, or vice versa, enabling equivalent reformulations.",
        "when_to_use": "When simplifying or restructuring complex negated conditions.",
    },
    {
        "name": "Conditional Proof",
        "category": "deductive",
        "description": "Temporarily assumes the antecedent and derives the consequent, thereby establishing the conditional statement as a whole.",
        "when_to_use": "When you want to prove an if-then statement by assuming the if-part and deriving the then-part.",
    },
    {
        "name": "Transitive Reasoning",
        "category": "deductive",
        "description": "If A relates to B and B relates to C under a transitive relation, then A relates to C. Chains relational steps together.",
        "when_to_use": "When connecting entities through a chain of relationships like ordering, implication, or subset inclusion.",
    },
    {
        "name": "Disjunction Introduction",
        "category": "deductive",
        "description": "From a known truth P, infers that P-or-Q is true for any proposition Q. Weakens a claim by adding alternatives.",
        "when_to_use": "When you need to establish a disjunctive claim and already know one disjunct is true.",
    },
    {
        "name": "Double Negation Elimination",
        "category": "deductive",
        "description": "From not-not-P, concludes P. Removes a double layer of negation to recover the original assertion.",
        "when_to_use": "When indirect reasoning has produced a doubly negated statement that needs simplification.",
    },
    # =========================================================================
    # INDUCTIVE (25)
    # =========================================================================
    {
        "name": "Enumerative Induction",
        "category": "inductive",
        "description": "Observes multiple instances sharing a property and generalizes that all members of the class share it. Strength grows with sample size and diversity.",
        "when_to_use": "When you have observed many consistent examples and want to form a general rule.",
    },
    {
        "name": "Statistical Generalization",
        "category": "inductive",
        "description": "Infers that what is true of a representative sample is approximately true of the population. Relies on sample size and randomness.",
        "when_to_use": "When extrapolating from a well-chosen sample to a larger population.",
    },
    {
        "name": "Statistical Syllogism",
        "category": "inductive",
        "description": "From the fact that most members of a group have a property, infers a specific member likely has it too.",
        "when_to_use": "When making predictions about an individual based on group-level statistical information.",
    },
    {
        "name": "Argument from Authority",
        "category": "inductive",
        "description": "Accepts a claim as likely true because a credible and relevant authority endorses it. Strength depends on the authority's expertise and track record.",
        "when_to_use": "When direct evidence is unavailable but a trustworthy expert has weighed in.",
    },
    {
        "name": "Argument from Testimony",
        "category": "inductive",
        "description": "Accepts a claim based on the reports of witnesses or informants, weighted by their reliability and consistency.",
        "when_to_use": "When relying on firsthand accounts as evidence for a conclusion.",
    },
    {
        "name": "Eliminative Induction",
        "category": "inductive",
        "description": "Systematically rules out competing hypotheses through observation, strengthening the remaining candidates. Each elimination increases confidence.",
        "when_to_use": "When you have a finite set of candidate explanations and can test them individually.",
    },
    {
        "name": "Trend Extrapolation",
        "category": "inductive",
        "description": "Extends an observed pattern or trend into the future, assuming the underlying conditions remain stable.",
        "when_to_use": "When past data shows a consistent trend and you need to forecast future values.",
    },
    {
        "name": "Inductive Generalization from Diverse Cases",
        "category": "inductive",
        "description": "Strengthens an inductive conclusion by drawing examples from maximally varied contexts rather than a narrow sample.",
        "when_to_use": "When you want a robust generalization and can gather evidence from very different situations.",
    },
    {
        "name": "Argument from Analogy (Inductive)",
        "category": "inductive",
        "description": "Notes similarities between two cases in known respects and infers similarity in an unknown respect. Probabilistic rather than certain.",
        "when_to_use": "When a well-understood precedent shares key features with a new situation.",
    },
    {
        "name": "Pattern Recognition",
        "category": "inductive",
        "description": "Identifies recurring regularities in data and projects them forward. The foundation of empirical learning.",
        "when_to_use": "When repeated observations suggest a systematic structure worth generalizing.",
    },
    {
        "name": "Negative Instance Analysis",
        "category": "inductive",
        "description": "Examines cases where the expected pattern fails and uses them to refine or bound the generalization.",
        "when_to_use": "When counterexamples appear and you need to adjust the scope of your inductive claim.",
    },
    {
        "name": "Mill's Method of Agreement",
        "category": "inductive",
        "description": "If two or more instances of a phenomenon share only one common factor, that factor is likely the cause.",
        "when_to_use": "When comparing cases that differ in many respects but all share one feature alongside the effect.",
    },
    {
        "name": "Mill's Method of Difference",
        "category": "inductive",
        "description": "If a case where the phenomenon occurs and one where it does not differ in only one factor, that factor is likely the cause.",
        "when_to_use": "When you have a near-identical pair of cases that differ only in one variable and in the outcome.",
    },
    {
        "name": "Mill's Joint Method",
        "category": "inductive",
        "description": "Combines the methods of agreement and difference: identifies common factors among positive cases that are absent from negative cases.",
        "when_to_use": "When you can analyze both positive and negative instances to triangulate the causal factor.",
    },
    {
        "name": "Mill's Method of Concomitant Variation",
        "category": "inductive",
        "description": "When a factor varies and the effect varies correspondingly, the two are likely causally connected.",
        "when_to_use": "When you observe that changes in one variable track changes in another across multiple observations.",
    },
    {
        "name": "Mill's Method of Residues",
        "category": "inductive",
        "description": "Subtracts the known effects of known causes from a phenomenon; whatever remains must be the effect of the remaining cause.",
        "when_to_use": "When part of an effect is already explained and you want to attribute the residual to an unexplained factor.",
    },
    {
        "name": "Accumulation of Evidence",
        "category": "inductive",
        "description": "Gathers converging lines of independent evidence that all point to the same conclusion, each line adding incremental support.",
        "when_to_use": "When no single piece of evidence is decisive but multiple independent sources all agree.",
    },
    {
        "name": "Inference to Regularity",
        "category": "inductive",
        "description": "From a large number of uniform observations, infers a lawlike regularity that holds generally.",
        "when_to_use": "When consistent repetition suggests a deeper lawlike connection rather than coincidence.",
    },
    {
        "name": "Predictive Validation",
        "category": "inductive",
        "description": "Tests a generalization by deriving novel predictions and checking them against new data. Successful predictions strengthen the generalization.",
        "when_to_use": "When you want to confirm an inductive hypothesis by seeing if its predictions hold in fresh cases.",
    },
    {
        "name": "Case-Based Reasoning",
        "category": "inductive",
        "description": "Solves a new problem by retrieving and adapting solutions from similar past cases stored in memory.",
        "when_to_use": "When a new situation closely resembles a previously solved case and the solution can be transferred.",
    },
    {
        "name": "Argument from Silence",
        "category": "inductive",
        "description": "Infers the absence or non-occurrence of something from the lack of expected evidence or mention of it.",
        "when_to_use": "When a thorough search for evidence of something turns up nothing, suggesting it may not exist.",
    },
    {
        "name": "Bootstrapping",
        "category": "inductive",
        "description": "Uses initial rough estimates to iteratively refine a model, with each iteration improving accuracy based on incoming data.",
        "when_to_use": "When starting with limited information but able to progressively improve estimates through feedback.",
    },
    {
        "name": "Convergent Evidence",
        "category": "inductive",
        "description": "Multiple independent methods or data sources pointing to the same conclusion provide stronger support than any single line of evidence.",
        "when_to_use": "When you can gather evidence from methodologically independent approaches.",
    },
    {
        "name": "Sampling and Estimation",
        "category": "inductive",
        "description": "Draws a representative subset from a population and uses it to estimate population-level parameters within confidence bounds.",
        "when_to_use": "When it is impractical to examine every case and a well-drawn sample can approximate the whole.",
    },
    {
        "name": "Proportional Syllogism",
        "category": "inductive",
        "description": "From the proportion of a group having a property, assigns a corresponding probability to a randomly chosen individual having it.",
        "when_to_use": "When you know the distribution in a reference class and want to estimate the likelihood for a specific case.",
    },
    # =========================================================================
    # ABDUCTIVE (25)
    # =========================================================================
    {
        "name": "Inference to the Best Explanation",
        "category": "abductive",
        "description": "Selects the hypothesis that best explains the observed evidence, balancing explanatory power, simplicity, and coherence.",
        "when_to_use": "When multiple hypotheses could account for the evidence and you need to choose the most plausible.",
    },
    {
        "name": "Occam's Razor",
        "category": "abductive",
        "description": "Prefers the simplest explanation that accounts for all the evidence, avoiding unnecessary assumptions or entities.",
        "when_to_use": "When competing explanations fit the data equally well and you need a tiebreaker.",
    },
    {
        "name": "Diagnostic Reasoning",
        "category": "abductive",
        "description": "Works backward from observed symptoms to infer the most likely underlying cause, iteratively narrowing possibilities.",
        "when_to_use": "When you observe a set of symptoms or signs and need to identify their root cause.",
    },
    {
        "name": "Retroduction",
        "category": "abductive",
        "description": "Starts with a surprising observation and reasons backward to a hypothesis that would make it unsurprising if true.",
        "when_to_use": "When an unexpected observation demands an explanation that renders it expected.",
    },
    {
        "name": "Hypothesis Generation",
        "category": "abductive",
        "description": "Creatively proposes candidate explanations for an observed phenomenon before testing or comparing them.",
        "when_to_use": "At the beginning of an inquiry when you need to brainstorm possible explanations.",
    },
    {
        "name": "Explanatory Coherence",
        "category": "abductive",
        "description": "Evaluates hypotheses by how well they cohere with other accepted beliefs and explain a wide range of evidence.",
        "when_to_use": "When judging which explanation integrates best with your existing knowledge.",
    },
    {
        "name": "Anomaly Resolution",
        "category": "abductive",
        "description": "Identifies observations that conflict with current understanding and seeks a revised explanation that accommodates them.",
        "when_to_use": "When you encounter data that does not fit existing theories and need to revise your model.",
    },
    {
        "name": "Surprise-Based Reasoning",
        "category": "abductive",
        "description": "Uses the degree of surprise an observation produces to guide the search for its explanation; more surprising facts demand better explanations.",
        "when_to_use": "When an observation is highly unexpected and you want to prioritize explanations that make it predictable.",
    },
    {
        "name": "Contrastive Explanation",
        "category": "abductive",
        "description": "Explains why one outcome occurred rather than an expected alternative, focusing on the differentiating factors.",
        "when_to_use": "When the question is not just why something happened but why it happened instead of something else.",
    },
    {
        "name": "Abductive Elimination",
        "category": "abductive",
        "description": "Generates a set of candidate explanations and eliminates those that fail to account for key evidence, leaving the best remaining.",
        "when_to_use": "When you can systematically test and discard inadequate explanations.",
    },
    {
        "name": "Common Cause Inference",
        "category": "abductive",
        "description": "Infers a shared underlying cause when two or more events are correlated but neither causes the other.",
        "when_to_use": "When correlated phenomena seem too coincidental to be independent and a hidden common factor is suspected.",
    },
    {
        "name": "Peirce's Abduction",
        "category": "abductive",
        "description": "Observes a surprising fact, considers that a hypothesis would make it expected, and provisionally adopts the hypothesis for testing.",
        "when_to_use": "When generating a working hypothesis to explain a puzzling observation before you can test it.",
    },
    {
        "name": "Theoretical Unification",
        "category": "abductive",
        "description": "Favors explanations that unify disparate phenomena under a single framework, increasing explanatory scope.",
        "when_to_use": "When seemingly unrelated observations might all follow from one underlying principle.",
    },
    {
        "name": "Contextual Interpretation",
        "category": "abductive",
        "description": "Interprets ambiguous evidence by considering the broader context in which it appears, selecting the reading that best fits.",
        "when_to_use": "When evidence is ambiguous and surrounding context can disambiguate its meaning.",
    },
    {
        "name": "Signal Extraction",
        "category": "abductive",
        "description": "Separates meaningful patterns from noise in data, identifying the underlying signal that best explains the observations.",
        "when_to_use": "When data is noisy and you need to identify the genuine pattern beneath random variation.",
    },
    {
        "name": "Mechanism Inference",
        "category": "abductive",
        "description": "Postulates an underlying mechanism that would produce the observed effects, grounding the explanation in a plausible process.",
        "when_to_use": "When you want not just to identify a cause but to explain how it produces the effect.",
    },
    {
        "name": "Eliminative Abduction",
        "category": "abductive",
        "description": "Systematically rules out all candidate explanations except one, which is accepted by default.",
        "when_to_use": "When you can enumerate all plausible explanations and definitively refute all but one.",
    },
    {
        "name": "Simplicity Preference",
        "category": "abductive",
        "description": "Among competing explanations, prefers the one with fewer free parameters, assumptions, or ad-hoc modifications.",
        "when_to_use": "When choosing between equally adequate explanations that differ in complexity.",
    },
    {
        "name": "Consilience of Inductions",
        "category": "abductive",
        "description": "Strengthens a hypothesis when it explains findings from multiple independent domains or lines of inquiry.",
        "when_to_use": "When a single explanation accounts for evidence from several independent areas.",
    },
    {
        "name": "Inference from Traces",
        "category": "abductive",
        "description": "Reconstructs past events from the traces or artifacts they left behind, selecting the most plausible historical account.",
        "when_to_use": "When you must reconstruct what happened from leftover evidence and residual marks.",
    },
    {
        "name": "Error Tracing",
        "category": "abductive",
        "description": "Works backward from an observed error or failure to identify the point in a process where things went wrong.",
        "when_to_use": "When debugging a failure and you need to locate the root cause in a chain of events.",
    },
    {
        "name": "Pattern Completion",
        "category": "abductive",
        "description": "Fills in missing elements of an incomplete pattern by inferring what would make the pattern whole and consistent.",
        "when_to_use": "When you have partial information that suggests an underlying structure with gaps to fill.",
    },
    {
        "name": "Latent Variable Inference",
        "category": "abductive",
        "description": "Posits unobserved variables that explain the structure of observed correlations, simplifying a complex set of relationships.",
        "when_to_use": "When observed variables show systematic correlations that suggest a hidden underlying factor.",
    },
    {
        "name": "Narrative Construction",
        "category": "abductive",
        "description": "Organizes disparate facts into a coherent story that explains how and why events unfolded as they did.",
        "when_to_use": "When you need to make sense of a sequence of events by constructing a plausible explanatory narrative.",
    },
    {
        "name": "Functional Explanation",
        "category": "abductive",
        "description": "Explains the existence or form of something by the function it serves or the role it plays in a larger system.",
        "when_to_use": "When understanding why something exists by identifying the purpose it fulfills.",
    },
    # =========================================================================
    # ANALOGICAL (25)
    # =========================================================================
    {
        "name": "Structural Analogy",
        "category": "analogical",
        "description": "Maps the relational structure of a well-understood source domain onto a target domain to generate inferences.",
        "when_to_use": "When two domains share relational structure even if their surface features differ.",
    },
    {
        "name": "Surface Analogy",
        "category": "analogical",
        "description": "Draws parallels based on superficial similarities between two cases, such as shared attributes or appearances.",
        "when_to_use": "When a quick comparison is needed and surface features provide a reasonable first approximation.",
    },
    {
        "name": "Proportional Analogy",
        "category": "analogical",
        "description": "Reasons that A is to B as C is to D, transferring the relationship observed in one pair to another.",
        "when_to_use": "When the relationship between two known items can illuminate the relationship between two others.",
    },
    {
        "name": "Metaphorical Reasoning",
        "category": "analogical",
        "description": "Uses metaphor to map concepts from a familiar domain to an abstract or unfamiliar one, enabling new insights.",
        "when_to_use": "When abstract concepts become clearer through comparison to concrete, familiar experiences.",
    },
    {
        "name": "Model-Based Reasoning",
        "category": "analogical",
        "description": "Constructs a simplified model of a complex system and reasons about the model to draw conclusions about the original.",
        "when_to_use": "When the real system is too complex to reason about directly and a simplified model captures the essentials.",
    },
    {
        "name": "Precedent-Based Reasoning",
        "category": "analogical",
        "description": "Uses the outcome of a prior similar case as a guide for how to handle or predict the outcome of a new case.",
        "when_to_use": "When a well-documented previous case is sufficiently similar to inform the current situation.",
    },
    {
        "name": "Cross-Domain Transfer",
        "category": "analogical",
        "description": "Applies insights, methods, or solutions from one field to a different field by identifying shared abstract structure.",
        "when_to_use": "When a solution in one domain might apply to a structurally similar problem in another.",
    },
    {
        "name": "Thought Experiment",
        "category": "analogical",
        "description": "Imagines a hypothetical scenario to explore the consequences of principles or test intuitions without physical experimentation.",
        "when_to_use": "When direct experimentation is impossible but reasoning through a scenario can clarify concepts.",
    },
    {
        "name": "Near Analogy",
        "category": "analogical",
        "description": "Draws comparisons between closely related domains that share many features, yielding high-confidence but limited novelty.",
        "when_to_use": "When domains are closely related and the transfer is straightforward and reliable.",
    },
    {
        "name": "Far Analogy",
        "category": "analogical",
        "description": "Draws comparisons between distant domains that share deep structural similarities despite surface differences, yielding novel insights.",
        "when_to_use": "When creative problem-solving requires looking beyond the immediate domain for inspiration.",
    },
    {
        "name": "Negative Analogy",
        "category": "analogical",
        "description": "Identifies where the analogy breaks down, using the differences to bound or qualify the conclusions drawn.",
        "when_to_use": "When you need to understand the limits of an analogy and avoid overgeneralization.",
    },
    {
        "name": "Exemplar Reasoning",
        "category": "analogical",
        "description": "Classifies or judges a new case by comparing it to a stored prototypical example rather than an abstract rule.",
        "when_to_use": "When you have a paradigmatic example and want to judge how closely a new case matches it.",
    },
    {
        "name": "Prototype Matching",
        "category": "analogical",
        "description": "Compares a new instance to an idealized prototype of a category to determine membership or typicality.",
        "when_to_use": "When categorizing something by its similarity to the most typical member of a group.",
    },
    {
        "name": "Scaling Reasoning",
        "category": "analogical",
        "description": "Infers how a phenomenon behaves at a different scale by analogy with known behavior at the current scale.",
        "when_to_use": "When predicting how something will change as its size, scope, or magnitude increases or decreases.",
    },
    {
        "name": "Synectics",
        "category": "analogical",
        "description": "Deliberately uses analogies from unrelated fields to stimulate creative thinking and generate novel solutions.",
        "when_to_use": "When brainstorming and you want to break free of conventional thinking through forced analogies.",
    },
    {
        "name": "Role Reversal",
        "category": "analogical",
        "description": "Swaps the positions or roles of entities in a scenario to gain new perspective on the relationships involved.",
        "when_to_use": "When examining a situation from a different vantage point reveals overlooked considerations.",
    },
    {
        "name": "Isomorphic Mapping",
        "category": "analogical",
        "description": "Identifies a one-to-one structural correspondence between two systems, allowing rigorous transfer of conclusions.",
        "when_to_use": "When two systems have identical abstract structure and results from one can be formally applied to the other.",
    },
    {
        "name": "Bridging Analogy",
        "category": "analogical",
        "description": "Uses an intermediate case that shares features with both the source and target to facilitate analogical transfer.",
        "when_to_use": "When the source and target are too dissimilar for direct analogy but a third case can bridge them.",
    },
    {
        "name": "Visual-Spatial Analogy",
        "category": "analogical",
        "description": "Maps spatial or visual relationships from one domain onto another, using geometric or topological correspondences.",
        "when_to_use": "When spatial reasoning in a familiar context can illuminate structure in an abstract domain.",
    },
    {
        "name": "Functional Analogy",
        "category": "analogical",
        "description": "Compares entities based on the function they serve rather than what they are, finding parallels in purpose across domains.",
        "when_to_use": "When things that look different serve the same role and insights about one illuminate the other.",
    },
    {
        "name": "Mimicry-Based Reasoning",
        "category": "analogical",
        "description": "Derives solutions by imitating strategies observed in nature or other systems that face analogous challenges.",
        "when_to_use": "When nature or other systems have already solved a similar problem through evolution or adaptation.",
    },
    {
        "name": "Parable Reasoning",
        "category": "analogical",
        "description": "Uses a simple illustrative story to convey and reason about a general principle applicable to the current situation.",
        "when_to_use": "When a concrete story makes an abstract principle vivid and easier to reason about.",
    },
    {
        "name": "Analogy with Constraints",
        "category": "analogical",
        "description": "Transfers knowledge from a source to a target while respecting known constraints that limit how far the analogy extends.",
        "when_to_use": "When the analogy is useful but known differences require restricting which inferences are transferred.",
    },
    {
        "name": "Template Matching",
        "category": "analogical",
        "description": "Recognizes that a new problem fits a known template or schema and applies the template's solution structure.",
        "when_to_use": "When a problem matches a well-known pattern with established solution approaches.",
    },
    {
        "name": "Dimensional Analogy",
        "category": "analogical",
        "description": "Understands a higher-dimensional concept by analogy with its lower-dimensional counterpart.",
        "when_to_use": "When reasoning about something in higher dimensions by first understanding the corresponding lower-dimensional case.",
    },
    # =========================================================================
    # CAUSAL (25)
    # =========================================================================
    {
        "name": "Causal Chain Analysis",
        "category": "causal",
        "description": "Traces a sequence of cause-and-effect links from an initial event to a final outcome, identifying each intermediate step.",
        "when_to_use": "When you need to understand how an initial event propagates through a series of effects to produce an outcome.",
    },
    {
        "name": "Counterfactual Reasoning",
        "category": "causal",
        "description": "Evaluates causation by asking what would have happened if a particular factor had been different.",
        "when_to_use": "When assessing whether a factor was genuinely causal by imagining its absence.",
    },
    {
        "name": "Root Cause Analysis",
        "category": "causal",
        "description": "Systematically works backward from an observed problem to identify the fundamental underlying cause rather than symptoms.",
        "when_to_use": "When you want to solve a problem at its source rather than treating surface symptoms.",
    },
    {
        "name": "Five Whys",
        "category": "causal",
        "description": "Iteratively asks why something happened, peeling back layers of causation until the root cause is reached.",
        "when_to_use": "When a quick, iterative deepening of causal inquiry is needed to find the root cause.",
    },
    {
        "name": "Fishbone Diagram Reasoning",
        "category": "causal",
        "description": "Organizes potential causes of an effect into categories branching from a central spine, enabling systematic exploration.",
        "when_to_use": "When you need to brainstorm and organize multiple possible causes of a complex effect.",
    },
    {
        "name": "Feedback Loop Analysis",
        "category": "causal",
        "description": "Identifies self-reinforcing or self-correcting cycles where effects feed back to amplify or dampen their causes.",
        "when_to_use": "When a system exhibits escalating or stabilizing behavior suggesting circular causal pathways.",
    },
    {
        "name": "Intervention Reasoning",
        "category": "causal",
        "description": "Determines causal effects by considering what happens when a variable is deliberately manipulated rather than merely observed.",
        "when_to_use": "When distinguishing genuine causation from mere correlation by reasoning about interventions.",
    },
    {
        "name": "Necessary vs Sufficient Cause Distinction",
        "category": "causal",
        "description": "Distinguishes between causes that must be present for an effect and causes that alone guarantee the effect.",
        "when_to_use": "When you need to clarify whether a factor is required for, or guarantees, an outcome.",
    },
    {
        "name": "Proximate vs Distal Cause Distinction",
        "category": "causal",
        "description": "Differentiates between immediate triggers and deeper background conditions, each contributing differently to an outcome.",
        "when_to_use": "When the immediate cause differs from the underlying enabling conditions and both matter.",
    },
    {
        "name": "Causal Overdetermination Analysis",
        "category": "causal",
        "description": "Recognizes when multiple independent causes each suffice to produce the effect, complicating simple causal attribution.",
        "when_to_use": "When an effect would have occurred even if any single cause had been removed.",
    },
    {
        "name": "Preemption Analysis",
        "category": "causal",
        "description": "Identifies cases where one causal process prevents another from completing, despite both being capable of producing the effect.",
        "when_to_use": "When two potential causes compete and one effectively preempts the other.",
    },
    {
        "name": "Causal Graph Reasoning",
        "category": "causal",
        "description": "Represents causal relationships as a directed graph and reads off conditional independencies and causal effects from its structure.",
        "when_to_use": "When complex causal relationships need to be represented and analyzed systematically.",
    },
    {
        "name": "Spurious Correlation Detection",
        "category": "causal",
        "description": "Identifies cases where two variables are correlated but neither causes the other, typically due to a confounding factor.",
        "when_to_use": "When a correlation might be misleading and you need to check for hidden confounders.",
    },
    {
        "name": "Dose-Response Reasoning",
        "category": "causal",
        "description": "Evaluates causation by checking whether more of the cause produces more of the effect in a graded fashion.",
        "when_to_use": "When a dose-response relationship would provide evidence for a causal link.",
    },
    {
        "name": "Temporal Precedence Analysis",
        "category": "causal",
        "description": "Checks that the proposed cause occurs before its effect in time, a necessary condition for causation.",
        "when_to_use": "When establishing the temporal order of events to support or undermine a causal claim.",
    },
    {
        "name": "Natural Experiment Reasoning",
        "category": "causal",
        "description": "Exploits naturally occurring variation that approximates a controlled experiment to infer causal effects.",
        "when_to_use": "When a true experiment is infeasible but a natural variation provides a quasi-experimental comparison.",
    },
    {
        "name": "Confound Identification",
        "category": "causal",
        "description": "Systematically identifies variables that could influence both the putative cause and effect, threatening causal inference.",
        "when_to_use": "When evaluating whether an observed relationship might be driven by an unmeasured third variable.",
    },
    {
        "name": "Mediation Analysis",
        "category": "causal",
        "description": "Identifies intermediate variables through which a cause transmits its effect, decomposing the causal pathway.",
        "when_to_use": "When you want to understand the mechanism by which a cause produces its effect.",
    },
    {
        "name": "Moderation Analysis",
        "category": "causal",
        "description": "Identifies conditions under which a causal effect is stronger, weaker, or reversed, revealing boundary conditions.",
        "when_to_use": "When a causal relationship seems to depend on the level of another variable.",
    },
    {
        "name": "Granger Causality Reasoning",
        "category": "causal",
        "description": "Infers potential causation from the fact that past values of one variable help predict future values of another beyond its own history.",
        "when_to_use": "When working with time-series data and testing whether one series provides predictive information about another.",
    },
    {
        "name": "Causal Mechanism Tracing",
        "category": "causal",
        "description": "Maps out the step-by-step process by which a cause produces an effect, verifying each link in the chain.",
        "when_to_use": "When you want to go beyond showing that X causes Y to explaining exactly how.",
    },
    {
        "name": "Inhibitory Cause Analysis",
        "category": "causal",
        "description": "Identifies factors that prevent or suppress an effect that would otherwise occur, acting as negative causes.",
        "when_to_use": "When understanding why something did not happen despite conditions that normally produce it.",
    },
    {
        "name": "Causal Sufficiency Analysis",
        "category": "causal",
        "description": "Determines the minimal set of conditions that, taken together, are sufficient to guarantee the effect.",
        "when_to_use": "When you need to identify the complete set of jointly sufficient conditions for an outcome.",
    },
    {
        "name": "INUS Condition Analysis",
        "category": "causal",
        "description": "Identifies causes as Insufficient but Necessary parts of Unnecessary but Sufficient conditions for an effect.",
        "when_to_use": "When a cause contributes to an outcome only in conjunction with other factors, and alternative sets of factors also suffice.",
    },
    {
        "name": "Cascade Effect Analysis",
        "category": "causal",
        "description": "Traces how a small initial cause triggers a sequence of increasingly large effects through a system.",
        "when_to_use": "When a small perturbation could amplify through a system and you need to anticipate downstream consequences.",
    },
    # =========================================================================
    # PROBABILISTIC (25)
    # =========================================================================
    {
        "name": "Bayesian Updating",
        "category": "probabilistic",
        "description": "Revises the probability of a hypothesis in light of new evidence using Bayes' theorem, combining prior belief with the likelihood of the evidence.",
        "when_to_use": "When new evidence arrives and you need to rationally update your degree of belief.",
    },
    {
        "name": "Prior Probability Assessment",
        "category": "probabilistic",
        "description": "Establishes the initial probability of a hypothesis before any specific evidence is considered, based on background knowledge.",
        "when_to_use": "When setting a starting point for probabilistic reasoning before gathering data.",
    },
    {
        "name": "Likelihood Ratio Analysis",
        "category": "probabilistic",
        "description": "Compares how probable the evidence is under competing hypotheses to determine which hypothesis the evidence favors.",
        "when_to_use": "When evaluating which of two hypotheses is better supported by a specific piece of evidence.",
    },
    {
        "name": "Base Rate Reasoning",
        "category": "probabilistic",
        "description": "Incorporates the prevalence of a condition in the relevant population when interpreting evidence, avoiding the base rate fallacy.",
        "when_to_use": "When diagnostic evidence needs to be interpreted in the context of how common the condition is.",
    },
    {
        "name": "Expected Value Calculation",
        "category": "probabilistic",
        "description": "Computes the probability-weighted average of all possible outcomes to determine the expected payoff of a decision.",
        "when_to_use": "When choosing between options with uncertain outcomes and you want to maximize average payoff.",
    },
    {
        "name": "Risk Assessment",
        "category": "probabilistic",
        "description": "Evaluates the probability and severity of potential negative outcomes to guide cautious decision-making.",
        "when_to_use": "When you need to weigh both how likely and how bad potential negative outcomes are.",
    },
    {
        "name": "Conditional Probability Reasoning",
        "category": "probabilistic",
        "description": "Calculates the probability of an event given that another event has occurred, distinguishing P(A|B) from P(B|A).",
        "when_to_use": "When the probability of interest depends on a known condition or context.",
    },
    {
        "name": "Monte Carlo Reasoning",
        "category": "probabilistic",
        "description": "Estimates outcomes by mentally simulating many random scenarios and observing the distribution of results.",
        "when_to_use": "When the system is too complex for analytical probability but you can reason through representative scenarios.",
    },
    {
        "name": "Confidence Interval Reasoning",
        "category": "probabilistic",
        "description": "Expresses uncertainty about an estimate as a range of plausible values rather than a single point, with a stated confidence level.",
        "when_to_use": "When you want to communicate not just your best estimate but also its precision.",
    },
    {
        "name": "Decision Under Uncertainty",
        "category": "probabilistic",
        "description": "Selects actions by evaluating their expected outcomes under different possible states of the world, weighted by probability.",
        "when_to_use": "When you must act despite incomplete knowledge of how the world will unfold.",
    },
    {
        "name": "Sensitivity Analysis",
        "category": "probabilistic",
        "description": "Tests how conclusions change when input assumptions are varied, identifying which assumptions matter most.",
        "when_to_use": "When you want to know which uncertain inputs have the biggest impact on your conclusion.",
    },
    {
        "name": "Probabilistic Independence Check",
        "category": "probabilistic",
        "description": "Determines whether two events are probabilistically independent, meaning knowledge of one does not change the probability of the other.",
        "when_to_use": "When combining probabilities and you need to know whether events are independent or correlated.",
    },
    {
        "name": "Law of Large Numbers Reasoning",
        "category": "probabilistic",
        "description": "Recognizes that as sample size grows, the observed average converges to the expected value, grounding long-run predictions.",
        "when_to_use": "When assessing whether a sample is large enough for its average to reliably estimate the true mean.",
    },
    {
        "name": "Regression to the Mean",
        "category": "probabilistic",
        "description": "Recognizes that extreme observations tend to be followed by less extreme ones, due to the role of random variation.",
        "when_to_use": "When an extreme result might be partly due to chance and a follow-up is likely to be less extreme.",
    },
    {
        "name": "Probabilistic Dominance",
        "category": "probabilistic",
        "description": "Identifies when one option is at least as good as another in every scenario and strictly better in some, making it unambiguously preferable.",
        "when_to_use": "When comparing options and one is clearly superior across all possible outcomes.",
    },
    {
        "name": "Information Value Analysis",
        "category": "probabilistic",
        "description": "Estimates the expected benefit of acquiring additional information before making a decision, balancing cost of inquiry against reduction in uncertainty.",
        "when_to_use": "When deciding whether to gather more data or act now with current knowledge.",
    },
    {
        "name": "Probability Calibration",
        "category": "probabilistic",
        "description": "Checks whether stated probabilities match actual frequencies over time, adjusting future estimates to improve accuracy.",
        "when_to_use": "When you want to ensure your probability estimates are well-calibrated to reality.",
    },
    {
        "name": "Conjunction Fallacy Avoidance",
        "category": "probabilistic",
        "description": "Recognizes that the probability of two events both occurring cannot exceed the probability of either alone.",
        "when_to_use": "When a specific detailed scenario feels more probable than a general one and you need to check your intuition.",
    },
    {
        "name": "Disjunction Probability",
        "category": "probabilistic",
        "description": "Calculates the probability that at least one of several events occurs, accounting for overlap to avoid double-counting.",
        "when_to_use": "When estimating the chance that any of several possible events will happen.",
    },
    {
        "name": "Posterior Predictive Reasoning",
        "category": "probabilistic",
        "description": "Uses the updated posterior distribution to make predictions about future observations, integrating over remaining uncertainty.",
        "when_to_use": "When you have updated your beliefs with data and want to predict what you will observe next.",
    },
    {
        "name": "Minimax Reasoning",
        "category": "probabilistic",
        "description": "Chooses the option that minimizes the maximum possible loss, providing a conservative guarantee under worst-case scenarios.",
        "when_to_use": "When the downside risk matters more than the expected value and you want worst-case protection.",
    },
    {
        "name": "Maximin Reasoning",
        "category": "probabilistic",
        "description": "Selects the action whose worst-case outcome is the best among all options, maximizing the minimum guaranteed payoff.",
        "when_to_use": "When you want to guarantee the best possible floor on your outcome regardless of uncertainty.",
    },
    {
        "name": "Probability Weighting",
        "category": "probabilistic",
        "description": "Adjusts for the tendency to overweight small probabilities and underweight large ones when evaluating risky options.",
        "when_to_use": "When intuitive risk perception might distort your evaluation of unlikely but impactful events.",
    },
    {
        "name": "Marginal Analysis",
        "category": "probabilistic",
        "description": "Evaluates the incremental change in outcome from a small change in input, determining whether further effort is worthwhile.",
        "when_to_use": "When deciding whether to invest one more unit of effort by comparing its marginal cost and benefit.",
    },
    {
        "name": "Scenario Probability Assessment",
        "category": "probabilistic",
        "description": "Assigns probabilities to distinct future scenarios and evaluates decisions across the probability-weighted set.",
        "when_to_use": "When planning under uncertainty and you can enumerate a few plausible future scenarios.",
    },
    # =========================================================================
    # HEURISTIC (25)
    # =========================================================================
    {
        "name": "Divide and Conquer",
        "category": "heuristic",
        "description": "Breaks a complex problem into smaller, independent subproblems, solves each, and combines the solutions.",
        "when_to_use": "When a problem is too large to tackle at once but decomposes into manageable pieces.",
    },
    {
        "name": "Means-End Analysis",
        "category": "heuristic",
        "description": "Identifies the difference between the current state and the goal, then selects actions that reduce this difference.",
        "when_to_use": "When you can clearly define both where you are and where you want to be.",
    },
    {
        "name": "Working Backwards",
        "category": "heuristic",
        "description": "Starts from the desired goal and reasons backward to determine the steps needed to reach it from the starting state.",
        "when_to_use": "When the goal is clear but the path forward from the start is not.",
    },
    {
        "name": "Hill Climbing",
        "category": "heuristic",
        "description": "Makes incremental changes that improve the current situation, always moving in the locally best direction.",
        "when_to_use": "When you can evaluate how good each step is and want to make steady progress toward a better state.",
    },
    {
        "name": "Generate and Test",
        "category": "heuristic",
        "description": "Produces candidate solutions and tests each against criteria, keeping those that pass and discarding those that fail.",
        "when_to_use": "When the solution space is small enough to enumerate or you can generate good candidates cheaply.",
    },
    {
        "name": "Satisficing",
        "category": "heuristic",
        "description": "Searches for a solution that meets minimum acceptability criteria rather than optimizing for the absolute best.",
        "when_to_use": "When finding the optimal solution is too costly and a good-enough solution suffices.",
    },
    {
        "name": "Recognition-Primed Decision",
        "category": "heuristic",
        "description": "Experienced practitioners rapidly match a situation to a known pattern and apply the associated action without deliberative analysis.",
        "when_to_use": "When time pressure demands quick action and you have deep experience in the domain.",
    },
    {
        "name": "Anchoring and Adjustment",
        "category": "heuristic",
        "description": "Starts from an initial reference point and adjusts from it, though adjustments are often insufficient.",
        "when_to_use": "When you have a reference value and need to estimate a related quantity by adjusting from it.",
    },
    {
        "name": "Availability Heuristic",
        "category": "heuristic",
        "description": "Judges the frequency or probability of events based on how easily examples come to mind, which can be useful but also misleading.",
        "when_to_use": "When making quick frequency judgments based on recalled instances, but be aware of potential bias.",
    },
    {
        "name": "Representativeness Heuristic",
        "category": "heuristic",
        "description": "Judges the probability of membership in a category based on how similar an instance is to the typical category member.",
        "when_to_use": "When quickly classifying something by its resemblance to a prototype, while watching for base rate neglect.",
    },
    {
        "name": "Elimination by Aspects",
        "category": "heuristic",
        "description": "Progressively eliminates options by checking them against criteria one at a time, removing all options that fail each criterion.",
        "when_to_use": "When comparing many options and you want a systematic way to narrow the field.",
    },
    {
        "name": "Constraint Relaxation",
        "category": "heuristic",
        "description": "Temporarily removes or loosens constraints to find a solution, then reintroduces constraints to refine it.",
        "when_to_use": "When the problem seems unsolvable under current constraints and loosening one might reveal a path.",
    },
    {
        "name": "Constraint Satisfaction",
        "category": "heuristic",
        "description": "Finds a solution that simultaneously satisfies all stated constraints, often by iteratively assigning values and backtracking.",
        "when_to_use": "When the problem is defined by a set of constraints and any solution meeting all of them is acceptable.",
    },
    {
        "name": "Greedy Approach",
        "category": "heuristic",
        "description": "Makes the locally optimal choice at each step, hoping that local optima lead to a global optimum or good-enough solution.",
        "when_to_use": "When making the best immediate choice at each step is likely to yield a good overall result.",
    },
    {
        "name": "Problem Reformulation",
        "category": "heuristic",
        "description": "Restates a difficult problem in a different form that makes it easier to solve, without changing the underlying question.",
        "when_to_use": "When the current framing of a problem makes it intractable but an equivalent reformulation might not.",
    },
    {
        "name": "Abstraction and Specialization",
        "category": "heuristic",
        "description": "Solves a more abstract or general version of the problem first, then specializes the solution to the specific case.",
        "when_to_use": "When solving the general case first provides a framework that can be narrowed to your specific problem.",
    },
    {
        "name": "Trial and Error",
        "category": "heuristic",
        "description": "Attempts a solution, observes the result, and iteratively adjusts based on feedback until success is achieved.",
        "when_to_use": "When the solution space is poorly understood and you can cheaply test and learn from attempts.",
    },
    {
        "name": "Random Restart",
        "category": "heuristic",
        "description": "When stuck in a local optimum, abandons the current approach and starts fresh from a new random starting point.",
        "when_to_use": "When progress has stalled and you suspect you are trapped in a suboptimal local solution.",
    },
    {
        "name": "Simulated Annealing Reasoning",
        "category": "heuristic",
        "description": "Accepts occasionally worse solutions early in the search to explore broadly, then gradually becomes more selective as the search progresses.",
        "when_to_use": "When you need to avoid getting trapped in local optima by allowing controlled exploration of worse options.",
    },
    {
        "name": "Pareto Analysis",
        "category": "heuristic",
        "description": "Focuses effort on the few factors that account for most of the effect, following the principle that roughly 20% of causes drive 80% of results.",
        "when_to_use": "When resources are limited and you want to focus on the highest-impact areas first.",
    },
    {
        "name": "Decomposition into Subgoals",
        "category": "heuristic",
        "description": "Breaks a complex goal into a sequence of intermediate subgoals, each achievable and leading toward the final objective.",
        "when_to_use": "When a large goal feels overwhelming but can be approached through a series of manageable milestones.",
    },
    {
        "name": "Heuristic Search",
        "category": "heuristic",
        "description": "Uses an evaluation function to estimate how promising each path is and explores the most promising paths first.",
        "when_to_use": "When the search space is too large for exhaustive search and a good heuristic can guide exploration.",
    },
    {
        "name": "Fast and Frugal Heuristic",
        "category": "heuristic",
        "description": "Uses minimal information and simple rules to make quick decisions that are often surprisingly accurate.",
        "when_to_use": "When time and information are limited and a simple decision rule can perform nearly as well as complex analysis.",
    },
    {
        "name": "Look-Ahead Planning",
        "category": "heuristic",
        "description": "Mentally simulates the consequences of candidate actions several steps into the future before committing.",
        "when_to_use": "When the immediate effect of an action differs from its long-term consequences and foresight is valuable.",
    },
    {
        "name": "Triage",
        "category": "heuristic",
        "description": "Prioritizes items by urgency and impact, allocating attention to the most critical issues first.",
        "when_to_use": "When facing multiple competing demands and you need to allocate limited resources to the highest-priority items.",
    },
    # =========================================================================
    # DIALECTICAL (25)
    # =========================================================================
    {
        "name": "Thesis-Antithesis-Synthesis",
        "category": "dialectical",
        "description": "Proposes an initial claim, considers its opposition, and integrates both into a higher-level synthesis that transcends the contradiction.",
        "when_to_use": "When two opposing positions each capture part of the truth and need to be reconciled.",
    },
    {
        "name": "Socratic Method",
        "category": "dialectical",
        "description": "Uses a series of probing questions to expose assumptions, reveal contradictions, and guide toward deeper understanding.",
        "when_to_use": "When testing the soundness of a position by systematically questioning its foundations.",
    },
    {
        "name": "Steelmanning",
        "category": "dialectical",
        "description": "Constructs the strongest possible version of an opposing argument before attempting to refute it.",
        "when_to_use": "When you want to ensure your rebuttal addresses the best version of the opposing view, not a weak caricature.",
    },
    {
        "name": "Devil's Advocate",
        "category": "dialectical",
        "description": "Deliberately argues against a position, even one you agree with, to test its robustness and uncover weaknesses.",
        "when_to_use": "When you want to stress-test a conclusion by actively seeking reasons it might be wrong.",
    },
    {
        "name": "Dialectical Questioning",
        "category": "dialectical",
        "description": "Alternates between affirming and challenging a proposition to progressively refine understanding.",
        "when_to_use": "When exploring a topic by iteratively strengthening and then questioning each emerging position.",
    },
    {
        "name": "Red Team / Blue Team",
        "category": "dialectical",
        "description": "One side attacks a position or plan while the other defends it, exposing vulnerabilities through adversarial testing.",
        "when_to_use": "When evaluating the robustness of a plan or argument by simulating an adversarial challenge.",
    },
    {
        "name": "Perspective Taking",
        "category": "dialectical",
        "description": "Deliberately adopts another viewpoint to understand how different stakeholders see the same situation.",
        "when_to_use": "When your own perspective might be too narrow and understanding other viewpoints would enrich your analysis.",
    },
    {
        "name": "Argument Mapping",
        "category": "dialectical",
        "description": "Visually lays out the logical structure of arguments, with premises, conclusions, objections, and rebuttals explicitly connected.",
        "when_to_use": "When a complex debate needs to be clarified by making the logical structure explicit.",
    },
    {
        "name": "Principle of Charity",
        "category": "dialectical",
        "description": "Interprets an ambiguous argument in the strongest, most reasonable way before evaluating it.",
        "when_to_use": "When an argument could be read in multiple ways and you want to engage with its best interpretation.",
    },
    {
        "name": "Reframing",
        "category": "dialectical",
        "description": "Re-describes a situation using a different frame or perspective, revealing aspects that were hidden under the original framing.",
        "when_to_use": "When the current framing of an issue obscures important considerations that a different frame would reveal.",
    },
    {
        "name": "Negotiation Reasoning",
        "category": "dialectical",
        "description": "Seeks mutually acceptable solutions by understanding each side's interests and finding creative compromises.",
        "when_to_use": "When parties have conflicting goals and a resolution requires understanding and balancing competing interests.",
    },
    {
        "name": "Burden of Proof Analysis",
        "category": "dialectical",
        "description": "Determines which side in a debate bears the obligation to provide evidence, and evaluates whether that burden has been met.",
        "when_to_use": "When there is disagreement about a claim and you need to establish who must provide supporting evidence.",
    },
    {
        "name": "Assumption Challenging",
        "category": "dialectical",
        "description": "Explicitly identifies and questions the hidden assumptions underlying a position to see if they hold up.",
        "when_to_use": "When a conclusion rests on unstated assumptions that may be false or questionable.",
    },
    {
        "name": "Concession and Qualification",
        "category": "dialectical",
        "description": "Acknowledges valid points in an opposing argument and refines one's own position to accommodate them.",
        "when_to_use": "When the opposing view has merit that your position should acknowledge to become more accurate.",
    },
    {
        "name": "Mutual Exclusion Testing",
        "category": "dialectical",
        "description": "Checks whether two positions are truly incompatible or whether they can coexist under a broader framework.",
        "when_to_use": "When apparent contradictions between views might dissolve under a more nuanced analysis.",
    },
    {
        "name": "Premortem Analysis",
        "category": "dialectical",
        "description": "Imagines that a plan has already failed and works backward to identify what went wrong, uncovering overlooked risks.",
        "when_to_use": "When planning an important initiative and you want to anticipate failure modes before they occur.",
    },
    {
        "name": "Postmortem Analysis",
        "category": "dialectical",
        "description": "After a completed effort, systematically reviews what worked, what failed, and why to extract lessons for the future.",
        "when_to_use": "When an effort is complete and you want to capture lessons learned for future improvement.",
    },
    {
        "name": "Stakeholder Analysis",
        "category": "dialectical",
        "description": "Identifies all parties affected by a decision and considers their distinct perspectives, interests, and potential objections.",
        "when_to_use": "When a decision affects multiple parties and you need to account for their different viewpoints.",
    },
    {
        "name": "Constructive Controversy",
        "category": "dialectical",
        "description": "Deliberately introduces disagreement within a group to improve the quality of reasoning and decisions.",
        "when_to_use": "When a group is converging too quickly and might benefit from structured disagreement.",
    },
    {
        "name": "Elenctic Refutation",
        "category": "dialectical",
        "description": "Shows that an interlocutor's beliefs are internally inconsistent, forcing a revision of at least one belief.",
        "when_to_use": "When someone holds a set of beliefs that cannot all be true simultaneously.",
    },
    {
        "name": "Dialectical Ladder",
        "category": "dialectical",
        "description": "Moves through progressively more refined positions, each incorporating insights from the previous round of debate.",
        "when_to_use": "When iterative rounds of critique and revision can lead to a progressively better position.",
    },
    {
        "name": "Balancing Test",
        "category": "dialectical",
        "description": "Weighs competing values or interests against each other to reach a balanced judgment when they conflict.",
        "when_to_use": "When two legitimate values or interests conflict and neither can be fully satisfied.",
    },
    {
        "name": "Adversarial Collaboration",
        "category": "dialectical",
        "description": "People who disagree work together to design tests that could resolve their disagreement, committing in advance to accept the results.",
        "when_to_use": "When a persistent disagreement could be resolved by jointly designing a decisive test.",
    },
    {
        "name": "Charitable Reconstruction",
        "category": "dialectical",
        "description": "Rebuilds an unclear or poorly stated argument in its most coherent and compelling form before evaluating it.",
        "when_to_use": "When an argument is poorly articulated but might contain a valid insight worth extracting.",
    },
    {
        "name": "Dialectical Pivot",
        "category": "dialectical",
        "description": "Recognizes when a line of argument has reached a dead end and deliberately shifts to a new approach or framing.",
        "when_to_use": "When continued pursuit of the current argumentative strategy is unproductive.",
    },
    # =========================================================================
    # FORMAL (25)
    # =========================================================================
    {
        "name": "Predicate Logic Reasoning",
        "category": "formal",
        "description": "Uses quantifiers and predicates to express and derive conclusions about properties of objects and relations between them.",
        "when_to_use": "When reasoning about properties and relationships across a domain of objects requires formal precision.",
    },
    {
        "name": "Propositional Logic Reasoning",
        "category": "formal",
        "description": "Evaluates compound propositions using truth-functional connectives to determine validity of arguments.",
        "when_to_use": "When the logical structure of an argument can be fully captured by and, or, not, and if-then connectives.",
    },
    {
        "name": "Modal Logic Reasoning",
        "category": "formal",
        "description": "Reasons about necessity and possibility, distinguishing what must be true, what could be true, and what cannot be true.",
        "when_to_use": "When the distinction between necessary truths, contingent truths, and impossibilities matters.",
    },
    {
        "name": "Deontic Reasoning",
        "category": "formal",
        "description": "Reasons about obligations, permissions, and prohibitions using formal logic of norms.",
        "when_to_use": "When analyzing what is required, permitted, or forbidden under a given set of norms or rules.",
    },
    {
        "name": "Temporal Logic Reasoning",
        "category": "formal",
        "description": "Reasons about propositions that change truth value over time, using operators like always, eventually, and until.",
        "when_to_use": "When the truth of statements depends on when they are evaluated and temporal ordering matters.",
    },
    {
        "name": "Set-Theoretic Reasoning",
        "category": "formal",
        "description": "Uses set operations like union, intersection, complement, and subset to reason about collections and their relationships.",
        "when_to_use": "When reasoning about groups, categories, and their overlaps and containment relationships.",
    },
    {
        "name": "Truth Table Analysis",
        "category": "formal",
        "description": "Systematically evaluates all possible truth value combinations of atomic propositions to determine the truth conditions of a compound statement.",
        "when_to_use": "When you need to verify whether a logical formula is a tautology, contradiction, or contingency.",
    },
    {
        "name": "Natural Deduction",
        "category": "formal",
        "description": "Derives conclusions through a series of small inference steps, each licensed by a formal rule, building proofs in a natural style.",
        "when_to_use": "When constructing a formal proof step by step using standard inference rules.",
    },
    {
        "name": "Resolution Refutation",
        "category": "formal",
        "description": "Converts statements to clausal form and repeatedly resolves complementary literals to derive a contradiction, proving validity.",
        "when_to_use": "When you want a mechanical procedure for checking the validity of an argument in propositional or predicate logic.",
    },
    {
        "name": "Lambda Abstraction",
        "category": "formal",
        "description": "Treats functions as first-class objects that can be created, passed, and applied, enabling formal reasoning about computation.",
        "when_to_use": "When reasoning about functions, substitution, and computation at an abstract level.",
    },
    {
        "name": "Type-Theoretic Reasoning",
        "category": "formal",
        "description": "Uses type assignments to ensure well-formedness and prevent category errors in formal reasoning.",
        "when_to_use": "When ensuring that operations are applied to appropriate kinds of objects and expressions are well-formed.",
    },
    {
        "name": "Fixed-Point Reasoning",
        "category": "formal",
        "description": "Finds values that are unchanged by a transformation, useful for defining recursive concepts and reaching stable states.",
        "when_to_use": "When analyzing self-referential definitions or iterative processes that converge to a stable state.",
    },
    {
        "name": "Invariant Maintenance",
        "category": "formal",
        "description": "Identifies a property that remains true throughout a process and uses it to prove facts about the final state.",
        "when_to_use": "When you can identify something that never changes despite transformations, and this constancy implies your conclusion.",
    },
    {
        "name": "Pigeonhole Principle",
        "category": "formal",
        "description": "If n items are placed into fewer than n containers, at least one container must hold more than one item.",
        "when_to_use": "When proving that some coincidence or collision must occur because there are more items than slots.",
    },
    {
        "name": "Combinatorial Reasoning",
        "category": "formal",
        "description": "Counts and analyzes the ways objects can be arranged, selected, or combined under constraints.",
        "when_to_use": "When you need to count possibilities or prove existence/non-existence by combinatorial argument.",
    },
    {
        "name": "Graph-Theoretic Reasoning",
        "category": "formal",
        "description": "Models relationships as nodes and edges in a graph and uses graph properties to derive conclusions.",
        "when_to_use": "When relationships between entities form a network structure that graph theory can analyze.",
    },
    {
        "name": "Recursive Reasoning",
        "category": "formal",
        "description": "Solves a problem by expressing its solution in terms of solutions to smaller instances of the same problem.",
        "when_to_use": "When a problem naturally decomposes into smaller copies of itself with a clear base case.",
    },
    {
        "name": "Formal Analogy (Category Theory)",
        "category": "formal",
        "description": "Identifies structure-preserving mappings between formal systems, transferring theorems from one to another via functors.",
        "when_to_use": "When two formal systems share abstract structure and results from one can be formally transported to the other.",
    },
    {
        "name": "Diagonalization",
        "category": "formal",
        "description": "Constructs a new object that differs from every member of a given list in at least one respect, proving the list is incomplete.",
        "when_to_use": "When proving that no enumeration can capture all objects of a certain kind.",
    },
    {
        "name": "Well-Ordering Reasoning",
        "category": "formal",
        "description": "Uses the fact that every nonempty subset of a well-ordered set has a least element to prove existence or termination.",
        "when_to_use": "When proving that a process must terminate or that a minimal counterexample must exist.",
    },
    {
        "name": "Symmetry Breaking",
        "category": "formal",
        "description": "Reduces the search space by recognizing symmetries in a problem and fixing one representative from each equivalence class.",
        "when_to_use": "When many cases are equivalent under symmetry and you can analyze just one representative per class.",
    },
    {
        "name": "Extremal Principle",
        "category": "formal",
        "description": "Considers the extreme case, such as the smallest, largest, or most constrained instance, to derive a general conclusion.",
        "when_to_use": "When analyzing the extreme or boundary case reveals something that must hold generally.",
    },
    {
        "name": "Encoding and Decoding",
        "category": "formal",
        "description": "Translates a problem from one representation into another where it is easier to solve, then translates the solution back.",
        "when_to_use": "When a different representation of the problem makes the solution more apparent.",
    },
    {
        "name": "Proof by Construction",
        "category": "formal",
        "description": "Proves existence of an object by explicitly constructing it rather than arguing indirectly for its existence.",
        "when_to_use": "When you need to show something exists and can produce a concrete example.",
    },
    {
        "name": "Impossibility Proof",
        "category": "formal",
        "description": "Proves that no solution of a certain kind can exist by deriving a contradiction from the assumption of its existence.",
        "when_to_use": "When you suspect something is impossible and want to prove it rigorously.",
    },
    # =========================================================================
    # METACOGNITIVE (25)
    # =========================================================================
    {
        "name": "Self-Monitoring",
        "category": "metacognitive",
        "description": "Continuously assesses one's own reasoning process for errors, biases, and gaps during problem-solving.",
        "when_to_use": "When engaged in complex reasoning and you want to catch mistakes as they happen rather than after.",
    },
    {
        "name": "Calibration Assessment",
        "category": "metacognitive",
        "description": "Evaluates how well one's confidence levels match actual accuracy, aiming to be neither overconfident nor underconfident.",
        "when_to_use": "When you want to check whether your certainty about conclusions is warranted by the evidence.",
    },
    {
        "name": "Epistemic Humility",
        "category": "metacognitive",
        "description": "Acknowledges the limits of one's own knowledge and reasoning, remaining open to the possibility of being wrong.",
        "when_to_use": "When making claims in areas of genuine uncertainty where overconfidence could lead to error.",
    },
    {
        "name": "Cognitive Load Management",
        "category": "metacognitive",
        "description": "Monitors and manages the amount of information being processed simultaneously to prevent overload and errors.",
        "when_to_use": "When a problem demands more working memory than is available and you need to simplify or externalize.",
    },
    {
        "name": "Bias Checking",
        "category": "metacognitive",
        "description": "Explicitly reviews one's reasoning for known cognitive biases such as confirmation bias, anchoring, or sunk cost fallacy.",
        "when_to_use": "When a conclusion feels too easy or too aligned with prior preferences and might be biased.",
    },
    {
        "name": "Confirmation Bias Mitigation",
        "category": "metacognitive",
        "description": "Actively seeks disconfirming evidence and counterarguments to avoid selectively attending to evidence that supports existing beliefs.",
        "when_to_use": "When you notice you are only finding evidence that supports your preferred conclusion.",
    },
    {
        "name": "Strategy Selection",
        "category": "metacognitive",
        "description": "Before diving in, considers which problem-solving approach is most appropriate for the type of problem at hand.",
        "when_to_use": "At the start of a problem when choosing the right approach can save significant effort.",
    },
    {
        "name": "Progress Monitoring",
        "category": "metacognitive",
        "description": "Periodically checks whether the current approach is making headway and considers switching strategies if it is not.",
        "when_to_use": "When you have been working on a problem for a while and want to assess whether you are on the right track.",
    },
    {
        "name": "Knowledge Gap Identification",
        "category": "metacognitive",
        "description": "Explicitly identifies what you do not know that would be relevant, guiding information-seeking behavior.",
        "when_to_use": "When you sense that missing information is limiting your ability to reason effectively.",
    },
    {
        "name": "Assumption Auditing",
        "category": "metacognitive",
        "description": "Enumerates and examines the assumptions underlying your reasoning to check whether they are justified.",
        "when_to_use": "When your conclusion depends on unstated premises that might not hold.",
    },
    {
        "name": "Reasoning Transparency",
        "category": "metacognitive",
        "description": "Makes one's reasoning steps explicit and examinable, allowing for external review and self-correction.",
        "when_to_use": "When you want to allow yourself or others to verify each step of your reasoning.",
    },
    {
        "name": "Emotional Awareness in Reasoning",
        "category": "metacognitive",
        "description": "Monitors whether emotional states are influencing judgment and compensates for any distortion they might introduce.",
        "when_to_use": "When strong emotions might be coloring your assessment of evidence or options.",
    },
    {
        "name": "Dunning-Kruger Awareness",
        "category": "metacognitive",
        "description": "Recognizes that low competence in a domain often correlates with overestimation of one's ability in that domain.",
        "when_to_use": "When entering an unfamiliar domain and you might not know enough to gauge your own competence accurately.",
    },
    {
        "name": "Reflective Equilibrium",
        "category": "metacognitive",
        "description": "Iteratively adjusts both general principles and specific judgments until they are mutually consistent.",
        "when_to_use": "When your principles and your intuitive judgments about specific cases conflict and both need revision.",
    },
    {
        "name": "Intellectual Courage",
        "category": "metacognitive",
        "description": "Willingness to follow an argument to its conclusion even when the result is uncomfortable or unpopular.",
        "when_to_use": "When honest reasoning points to an inconvenient conclusion that might be tempting to avoid.",
    },
    {
        "name": "Scope Sensitivity Check",
        "category": "metacognitive",
        "description": "Verifies that one's valuation or concern scales appropriately with the magnitude of the thing being assessed.",
        "when_to_use": "When you suspect your response to a quantity does not properly scale with its actual size.",
    },
    {
        "name": "Decision Journaling",
        "category": "metacognitive",
        "description": "Records predictions, reasoning, and confidence levels at the time of a decision to enable later review and learning.",
        "when_to_use": "When you want to learn from past decisions by comparing predictions to outcomes.",
    },
    {
        "name": "Sunk Cost Awareness",
        "category": "metacognitive",
        "description": "Recognizes when past irrecoverable investments are inappropriately influencing current decisions and corrects for this.",
        "when_to_use": "When you catch yourself continuing a course of action mainly because of what you have already invested.",
    },
    {
        "name": "Framing Effect Awareness",
        "category": "metacognitive",
        "description": "Recognizes that how a problem is framed can bias the conclusion and deliberately reframes to check for consistency.",
        "when_to_use": "When the way a question is phrased might be leading you toward a particular answer.",
    },
    {
        "name": "Outside View",
        "category": "metacognitive",
        "description": "Steps back from the specifics of a case and considers what typically happens in the reference class of similar cases.",
        "when_to_use": "When you are immersed in details and need to ground your estimate in the statistical base rate.",
    },
    {
        "name": "Inside View vs Outside View Comparison",
        "category": "metacognitive",
        "description": "Compares the prediction from detailed analysis of the specific case with the base rate from similar past cases.",
        "when_to_use": "When you want to check whether your detailed inside analysis aligns with what reference classes suggest.",
    },
    {
        "name": "Cognitive Debiasing",
        "category": "metacognitive",
        "description": "Applies specific techniques to counteract known cognitive biases, such as considering the opposite or using reference classes.",
        "when_to_use": "When a known bias might be affecting your reasoning and you want to apply a corrective technique.",
    },
    {
        "name": "Meta-Reasoning",
        "category": "metacognitive",
        "description": "Reasons about one's own reasoning process, including when to stop deliberating and when to seek more information.",
        "when_to_use": "When you need to decide how much more thinking or information-gathering is warranted before acting.",
    },
    {
        "name": "Epistemic Status Tagging",
        "category": "metacognitive",
        "description": "Explicitly labels each claim with its evidential status: certain, probable, speculative, or unknown.",
        "when_to_use": "When communicating conclusions and you want to be clear about how much confidence each one deserves.",
    },
    {
        "name": "Belief Revision Protocol",
        "category": "metacognitive",
        "description": "Follows a systematic process for updating beliefs when new evidence arrives, ensuring consistency and proportionality.",
        "when_to_use": "When new information challenges existing beliefs and you need a disciplined approach to updating.",
    },
    # =========================================================================
    # ADDITIONAL PATTERNS TO REACH ~250
    # =========================================================================
    # More causal
    {
        "name": "Systematic Factor Analysis",
        "category": "causal",
        "description": "Methodically varies one factor at a time while holding others constant to isolate causal contributions.",
        "when_to_use": "When multiple factors could be responsible and you need to isolate which ones matter.",
    },
    # More probabilistic
    {
        "name": "Gambler's Fallacy Avoidance",
        "category": "probabilistic",
        "description": "Recognizes that past independent random outcomes do not affect future probabilities, avoiding the false belief that outcomes are due.",
        "when_to_use": "When tempted to believe a random process is due for a particular outcome after a run of different outcomes.",
    },
    {
        "name": "Expected Utility Maximization",
        "category": "probabilistic",
        "description": "Chooses the action that maximizes the probability-weighted utility across all possible outcomes, accounting for risk preferences.",
        "when_to_use": "When decisions involve both uncertainty and varying degrees of desirability of outcomes.",
    },
    # More heuristic
    {
        "name": "Analogy-Based Estimation",
        "category": "heuristic",
        "description": "Estimates an unknown quantity by comparing it to a known similar quantity and adjusting for differences.",
        "when_to_use": "When you lack direct data but have a comparable reference point you can adjust from.",
    },
    {
        "name": "Fermi Estimation",
        "category": "heuristic",
        "description": "Breaks an estimation problem into several factors that can each be roughly estimated, then combines them multiplicatively.",
        "when_to_use": "When you need a rough order-of-magnitude estimate for a quantity that cannot be directly measured.",
    },
    {
        "name": "Boundary Testing",
        "category": "heuristic",
        "description": "Tests a proposed solution or rule at extreme or edge-case values to check whether it still holds or breaks down.",
        "when_to_use": "When you want to find the limits of applicability of a rule or solution by pushing it to extremes.",
    },
    {
        "name": "Rubber Duck Reasoning",
        "category": "heuristic",
        "description": "Explains the problem and reasoning step by step to an imaginary listener, often revealing gaps or errors in the process.",
        "when_to_use": "When you are stuck and articulating your reasoning out loud might expose the flaw.",
    },
    # More dialectical
    {
        "name": "Inversion",
        "category": "dialectical",
        "description": "Instead of asking how to achieve a goal, asks how to guarantee failure, then avoids those failure modes.",
        "when_to_use": "When thinking about what to do is hard but thinking about what to avoid is easier.",
    },
    {
        "name": "Taboo Your Words",
        "category": "dialectical",
        "description": "Forces oneself to explain a concept without using its usual label, revealing whether genuine understanding underlies the terminology.",
        "when_to_use": "When a key term might be masking confusion and explaining the concept without it would test understanding.",
    },
    # More formal
    {
        "name": "Counting Argument",
        "category": "formal",
        "description": "Proves a claim by counting the same set of objects in two different ways and equating the results.",
        "when_to_use": "When a combinatorial identity or existence result follows from two different counting approaches.",
    },
    # More metacognitive
    {
        "name": "Pre-Commitment Strategy",
        "category": "metacognitive",
        "description": "Decides in advance what evidence or outcome would cause you to change your mind, binding yourself against motivated reasoning.",
        "when_to_use": "When you want to ensure future evidence is evaluated fairly rather than rationalized away.",
    },
    {
        "name": "Murphyjitsu",
        "category": "metacognitive",
        "description": "Mentally simulates your plan, asking at each step whether failure would be surprising, and strengthens weak points until it would be.",
        "when_to_use": "When stress-testing a plan by making it robust against foreseeable failure modes.",
    },
    # More inductive
    {
        "name": "Crucical Experiment Reasoning",
        "category": "inductive",
        "description": "Designs an observation that would decisively distinguish between two competing hypotheses, maximizing evidential value.",
        "when_to_use": "When two hypotheses are both consistent with existing evidence and you need a test to separate them.",
    },
    # More abductive
    {
        "name": "Competing Hypotheses Matrix",
        "category": "abductive",
        "description": "Lists all candidate hypotheses and systematically evaluates each against every piece of evidence in a matrix format.",
        "when_to_use": "When you need a structured way to compare multiple hypotheses against multiple pieces of evidence.",
    },
    # Scientific reasoning (assigned to existing categories)
    {
        "name": "Hypothesis Testing",
        "category": "inductive",
        "description": "Formulates a testable hypothesis, derives predictions, collects data, and evaluates whether the data supports or refutes the hypothesis.",
        "when_to_use": "When a claim can be formulated as a testable prediction and data can be gathered to evaluate it.",
    },
    {
        "name": "Control Variable Reasoning",
        "category": "causal",
        "description": "Holds all variables constant except the one under investigation to isolate its specific effect.",
        "when_to_use": "When testing a causal claim requires ensuring that observed effects are not due to confounding variables.",
    },
    {
        "name": "Falsificationism",
        "category": "inductive",
        "description": "Prioritizes attempts to falsify a hypothesis over attempts to confirm it, as a single counterexample can disprove a universal claim.",
        "when_to_use": "When you want to rigorously test a hypothesis by actively seeking evidence that would disprove it.",
    },
    {
        "name": "Reproducibility Reasoning",
        "category": "inductive",
        "description": "Requires that a finding be independently replicable before accepting it as reliable, guarding against flukes and errors.",
        "when_to_use": "When evaluating whether a result is robust enough to trust by asking if it can be reproduced.",
    },
    {
        "name": "Operational Definition",
        "category": "formal",
        "description": "Defines a concept in terms of the specific operations or measurements used to detect or quantify it, ensuring precision.",
        "when_to_use": "When a vague concept needs to be made precise enough for testing or measurement.",
    },
    {
        "name": "Null Hypothesis Reasoning",
        "category": "probabilistic",
        "description": "Assumes no effect or no difference as the default and requires evidence strong enough to reject this default assumption.",
        "when_to_use": "When evaluating whether observed data provides sufficient evidence to conclude a real effect exists.",
    },
    {
        "name": "Effect Size Reasoning",
        "category": "probabilistic",
        "description": "Goes beyond statistical significance to assess the practical magnitude of an observed effect.",
        "when_to_use": "When you need to know not just whether an effect exists but whether it is large enough to matter.",
    },
    {
        "name": "Selection Bias Detection",
        "category": "metacognitive",
        "description": "Identifies whether the sample or evidence you are reasoning from was collected in a systematically non-representative way.",
        "when_to_use": "When the process by which evidence was gathered might systematically exclude relevant cases.",
    },
    {
        "name": "Survivorship Bias Awareness",
        "category": "metacognitive",
        "description": "Recognizes that visible successes may not be representative because failures are hidden, leading to distorted conclusions.",
        "when_to_use": "When drawing conclusions from successful cases without accounting for the unseen failures.",
    },
    {
        "name": "Hindsight Bias Awareness",
        "category": "metacognitive",
        "description": "Recognizes the tendency to see past events as more predictable than they actually were and compensates for it.",
        "when_to_use": "When evaluating a past decision and you might be unfairly judging it with the benefit of hindsight.",
    },
]
