"""Hardcoded list of ~250 instruction complexity types for seed data generation."""

from __future__ import annotations

INSTRUCTION_COMPLEXITIES: list[dict[str, str]] = [
    # =========================================================================
    # SIMPLIFICATION STYLES
    # =========================================================================
    {
        "name": "Explain like I'm 5",
        "level": "simple",
        "ambiguity": "low",
        "description": "Requires distilling a concept to its absolute simplest form using vocabulary and analogies a young child would understand.",
        "example": "Explain like I'm 5: why do we need to sleep?",
    },
    {
        "name": "One sentence summary",
        "level": "simple",
        "ambiguity": "low",
        "description": "Demands extreme compression of information into a single grammatically complete sentence.",
        "example": "Summarize the concept in exactly one sentence.",
    },
    {
        "name": "TL;DR",
        "level": "simple",
        "ambiguity": "low",
        "description": "Asks for the most essential takeaway in a very brief format, stripping away all nuance and detail.",
        "example": "Give me the TL;DR of this process.",
    },
    {
        "name": "Elevator pitch",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires a persuasive, concise explanation deliverable in about 30-60 seconds, balancing clarity with impact.",
        "example": "Give me an elevator pitch for this approach.",
    },
    {
        "name": "Three-word answer",
        "level": "simple",
        "ambiguity": "moderate",
        "description": "Forces extreme brevity by limiting the response to exactly three words, requiring careful word selection.",
        "example": "Describe this concept in exactly three words.",
    },
    {
        "name": "Headline version",
        "level": "simple",
        "ambiguity": "low",
        "description": "Asks for a newspaper-headline-style summary that captures the core point in a punchy, attention-grabbing phrase.",
        "example": "Write a headline that captures the main idea.",
    },
    {
        "name": "Tweet-length explanation",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Constrains the explanation to roughly 280 characters, forcing extreme conciseness while remaining informative.",
        "example": "Explain this concept in a single tweet.",
    },
    {
        "name": "Back-of-napkin sketch",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for an informal, rough outline capturing only the most essential elements as if scribbled quickly.",
        "example": "Give me the back-of-napkin version of this plan.",
    },
    {
        "name": "Plain English rewrite",
        "level": "simple",
        "ambiguity": "low",
        "description": "Requires translating technical or formal language into everyday conversational English without losing meaning.",
        "example": "Rewrite this in plain English that anyone could understand.",
    },
    {
        "name": "One-word answer",
        "level": "simple",
        "ambiguity": "moderate",
        "description": "Demands collapsing complex nuance into a single carefully chosen word.",
        "example": "If you had to pick one word to describe this, what would it be?",
    },
    {
        "name": "Haiku summary",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires distilling information into the 5-7-5 syllable haiku format, balancing constraint with meaning.",
        "example": "Summarize the key insight as a haiku.",
    },
    {
        "name": "Bumper sticker",
        "level": "simple",
        "ambiguity": "moderate",
        "description": "Asks for a catchy, memorable slogan-length summary that could fit on a bumper sticker.",
        "example": "Boil this down to a bumper sticker slogan.",
    },
    # =========================================================================
    # STRUCTURED APPROACHES
    # =========================================================================
    {
        "name": "Step by step",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Requires breaking down a process or explanation into clearly ordered sequential steps.",
        "example": "Walk me through this step by step.",
    },
    {
        "name": "First principles breakdown",
        "level": "complex",
        "ambiguity": "low",
        "description": "Demands deconstructing a topic to its most fundamental truths and rebuilding understanding from the ground up.",
        "example": "Break this down from first principles.",
    },
    {
        "name": "Pros and cons",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Requires a balanced analysis listing advantages and disadvantages in a structured two-column format.",
        "example": "List the pros and cons of this approach.",
    },
    {
        "name": "Decision matrix",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for a weighted multi-criteria evaluation framework comparing options across several dimensions.",
        "example": "Create a decision matrix comparing these three options.",
    },
    {
        "name": "Flowchart logic",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires expressing a process as a series of conditional branches and decision points.",
        "example": "Describe this process as a flowchart with decision points.",
    },
    {
        "name": "Numbered list",
        "level": "simple",
        "ambiguity": "none",
        "description": "Asks for information organized as a clearly numbered sequential list for easy scanning.",
        "example": "Give me a numbered list of the key factors.",
    },
    {
        "name": "Bullet points",
        "level": "simple",
        "ambiguity": "none",
        "description": "Requests information formatted as concise bullet points without narrative prose.",
        "example": "Break this down into bullet points.",
    },
    {
        "name": "Table format",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires organizing information into rows and columns for structured comparison or reference.",
        "example": "Present this information as a table.",
    },
    {
        "name": "Mind map structure",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for a hierarchical, branching representation of concepts and their relationships.",
        "example": "Organize these ideas as a mind map with branches and sub-branches.",
    },
    {
        "name": "Timeline",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires arranging information chronologically along a temporal sequence.",
        "example": "Lay out the key milestones on a timeline.",
    },
    {
        "name": "SWOT analysis",
        "level": "complex",
        "ambiguity": "low",
        "description": "Demands a structured assessment across strengths, weaknesses, opportunities, and threats.",
        "example": "Do a SWOT analysis of this strategy.",
    },
    {
        "name": "Cause and effect chain",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires tracing cascading consequences from an initial cause through a sequence of effects.",
        "example": "Map out the cause and effect chain for this situation.",
    },
    {
        "name": "Taxonomy classification",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for organizing items into a hierarchical classification system with clear categories and subcategories.",
        "example": "Classify these items into a clear taxonomy.",
    },
    {
        "name": "Priority ranking",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires ordering items by importance or urgency with justification for the ranking.",
        "example": "Rank these items by priority and explain your reasoning.",
    },
    {
        "name": "Before and after comparison",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for a structured comparison showing the state of something before and after a change.",
        "example": "Show the before and after for this change.",
    },
    {
        "name": "Root cause analysis",
        "level": "expert",
        "ambiguity": "low",
        "description": "Demands systematic investigation to identify the fundamental underlying cause rather than surface symptoms.",
        "example": "Perform a root cause analysis to find the underlying issue.",
    },
    {
        "name": "Five Whys",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires iteratively asking 'why' five times to drill down from a symptom to a root cause.",
        "example": "Apply the Five Whys technique to get to the bottom of this problem.",
    },
    {
        "name": "Pyramid principle",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for structuring information top-down: leading with the conclusion, then supporting arguments, then details.",
        "example": "Structure your answer using the pyramid principle: conclusion first, then supporting points.",
    },
    {
        "name": "Issue tree",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires decomposing a problem into mutually exclusive, collectively exhaustive sub-issues in a tree structure.",
        "example": "Break this problem into an issue tree with MECE branches.",
    },
    # =========================================================================
    # PEDAGOGICAL APPROACHES
    # =========================================================================
    {
        "name": "Socratic questioning",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for a series of probing questions that guide the learner to discover the answer through their own reasoning.",
        "example": "Use Socratic questioning to help me understand this concept.",
    },
    {
        "name": "Worked example",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Requires demonstrating the complete solution process step by step on a concrete instance.",
        "example": "Show me a fully worked example of this process.",
    },
    {
        "name": "Scaffolded explanation",
        "level": "complex",
        "ambiguity": "low",
        "description": "Demands building understanding incrementally, starting from what the learner already knows and gradually adding complexity.",
        "example": "Explain this with scaffolding, starting from basic concepts and building up.",
    },
    {
        "name": "Compare and contrast",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Requires identifying both similarities and differences between two or more items in a structured way.",
        "example": "Compare and contrast these two approaches.",
    },
    {
        "name": "Teach it back",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for an explanation structured as if teaching the concept to someone else, reinforcing understanding through restatement.",
        "example": "Explain this as if you're teaching it to a colleague who knows nothing about it.",
    },
    {
        "name": "Progressive disclosure",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires revealing information in layers, starting with the simplest overview and adding detail with each pass.",
        "example": "Explain this in three levels: beginner, intermediate, and advanced.",
    },
    {
        "name": "Analogy-based explanation",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Demands explaining a concept primarily through analogies to more familiar domains.",
        "example": "Explain this using an analogy from everyday life.",
    },
    {
        "name": "Common misconceptions",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires identifying and correcting widespread misunderstandings about a topic.",
        "example": "What are the most common misconceptions about this, and why are they wrong?",
    },
    {
        "name": "Knowledge check",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for quiz-style questions to verify comprehension of the material just presented.",
        "example": "After your explanation, give me three questions to check my understanding.",
    },
    {
        "name": "Prerequisite mapping",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires identifying what background knowledge is needed before tackling the main concept.",
        "example": "What do I need to know before I can understand this topic?",
    },
    {
        "name": "Concrete to abstract",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for starting with tangible, specific examples and gradually moving toward the general principle.",
        "example": "Start with a concrete example and then generalize to the abstract rule.",
    },
    {
        "name": "Abstract to concrete",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for starting with the general principle and then grounding it with specific, tangible examples.",
        "example": "State the general principle first, then give me concrete examples.",
    },
    {
        "name": "Spaced repetition cues",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires creating flashcard-style question-answer pairs optimized for long-term retention.",
        "example": "Turn the key points into flashcard-style Q&A pairs for memorization.",
    },
    {
        "name": "Deliberate practice drill",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for targeted exercises that isolate and strengthen specific sub-skills.",
        "example": "Design a set of practice exercises that target the hardest part of this skill.",
    },
    {
        "name": "Learning objectives first",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires stating clear, measurable learning outcomes before delivering the content.",
        "example": "Start by listing what I should be able to do after reading your explanation.",
    },
    {
        "name": "Storytelling explanation",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for wrapping the explanation in a narrative structure with characters, conflict, and resolution.",
        "example": "Explain this concept through a short story.",
    },
    # =========================================================================
    # CONSTRAINT-BASED
    # =========================================================================
    {
        "name": "Under 100 words",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Imposes a strict word count ceiling, forcing conciseness without sacrificing completeness.",
        "example": "Explain this in under 100 words.",
    },
    {
        "name": "Without jargon",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Prohibits specialized terminology, requiring the use of only common everyday vocabulary.",
        "example": "Explain this without using any technical jargon.",
    },
    {
        "name": "Using only analogies",
        "level": "complex",
        "ambiguity": "low",
        "description": "Restricts the explanation to analogies only, never directly naming or defining the concept itself.",
        "example": "Explain this using only analogies, never stating the concept directly.",
    },
    {
        "name": "In bullet points only",
        "level": "simple",
        "ambiguity": "none",
        "description": "Prohibits prose paragraphs; all information must be in bullet point format.",
        "example": "Answer entirely in bullet points, no paragraphs.",
    },
    {
        "name": "No examples allowed",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires explaining purely through definitions and abstractions without any concrete examples.",
        "example": "Explain this concept without giving any examples at all.",
    },
    {
        "name": "Only using questions",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Restricts the response to only questions, guiding the reader to the answer through interrogation.",
        "example": "Respond only with questions that would lead me to the answer.",
    },
    {
        "name": "In exactly five sentences",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Imposes a precise sentence count, requiring careful allocation of information across exactly five statements.",
        "example": "Explain this in exactly five sentences, no more, no less.",
    },
    {
        "name": "Using a single paragraph",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Constrains the entire response to one cohesive paragraph with no line breaks.",
        "example": "Explain this in a single paragraph.",
    },
    {
        "name": "Without using the word",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires explaining a concept while avoiding the use of its name or key associated terms.",
        "example": "Explain this concept without ever using its name.",
    },
    {
        "name": "Using only monosyllables",
        "level": "complex",
        "ambiguity": "low",
        "description": "Restricts every word to a single syllable, dramatically limiting vocabulary while requiring clarity.",
        "example": "Explain this using only one-syllable words.",
    },
    {
        "name": "As a list of do's and don'ts",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Requires framing the information as actionable behavioral guidance in positive and negative forms.",
        "example": "Give me a list of do's and don'ts for this.",
    },
    {
        "name": "Maximum three bullet points",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Limits the response to at most three bullet points, forcing prioritization of the most critical information.",
        "example": "Summarize this in three bullet points max.",
    },
    {
        "name": "In ASCII art",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires representing the information visually using only text characters and whitespace.",
        "example": "Illustrate this concept using ASCII art.",
    },
    {
        "name": "As a formula or equation",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for expressing a relationship or process in a mathematical or symbolic formula.",
        "example": "Express the core idea as a formula or equation.",
    },
    {
        "name": "In reverse order",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires presenting information starting from the conclusion and working backward to the beginning.",
        "example": "Explain this in reverse chronological order, starting from the end result.",
    },
    {
        "name": "Under 50 words",
        "level": "complex",
        "ambiguity": "none",
        "description": "Imposes a very tight word limit that demands extreme editorial discipline.",
        "example": "Explain this in under 50 words.",
    },
    {
        "name": "Using exactly one analogy",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Restricts the explanation to a single well-chosen analogy that must carry the full weight of understanding.",
        "example": "Pick one analogy and use it to explain the entire concept.",
    },
    {
        "name": "As an acronym",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Requires encoding the key points as a memorable acronym with each letter standing for a concept.",
        "example": "Create an acronym that captures the essential steps of this process.",
    },
    {
        "name": "In passive voice only",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Constrains the grammatical voice, requiring all sentences be written in passive construction.",
        "example": "Explain this using only passive voice.",
    },
    # =========================================================================
    # PERSPECTIVE SHIFTS
    # =========================================================================
    {
        "name": "From a beginner's perspective",
        "level": "simple",
        "ambiguity": "low",
        "description": "Requires assuming zero prior knowledge and explaining as if the reader has never encountered the topic.",
        "example": "Explain this as if I've never heard of it before.",
    },
    {
        "name": "As a skeptic",
        "level": "complex",
        "ambiguity": "low",
        "description": "Demands adopting a questioning, doubt-driven stance that challenges every claim and assumption.",
        "example": "Approach this as a skeptic. What would you question?",
    },
    {
        "name": "Playing devil's advocate",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires arguing against the prevailing or obvious position, even if the responder agrees with it.",
        "example": "Play devil's advocate against this idea.",
    },
    {
        "name": "From an expert's perspective",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires assuming deep domain knowledge and using precise technical language appropriate for specialists.",
        "example": "Explain this at an expert level, assuming I have deep background knowledge.",
    },
    {
        "name": "From a child's perspective",
        "level": "simple",
        "ambiguity": "moderate",
        "description": "Asks for framing the explanation through the lens of a child's worldview and limited experience.",
        "example": "How would a curious 8-year-old describe this?",
    },
    {
        "name": "From the opposing viewpoint",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires presenting the strongest possible case for the side that disagrees with the stated position.",
        "example": "Explain the strongest argument from the opposing side.",
    },
    {
        "name": "As a practitioner",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Demands a practical, hands-on perspective focused on real-world application rather than theory.",
        "example": "Explain this from the perspective of someone who does this every day.",
    },
    {
        "name": "Historical perspective",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires framing the topic in the context of how it evolved over time and how past thinkers understood it.",
        "example": "How would someone from 100 years ago view this concept?",
    },
    {
        "name": "Cross-cultural perspective",
        "level": "expert",
        "ambiguity": "moderate",
        "description": "Asks for examining how the concept is understood or applied differently across various cultures.",
        "example": "How might this concept be understood differently across cultures?",
    },
    {
        "name": "Future perspective",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires speculating about how the concept will evolve or be viewed in the future.",
        "example": "How might people 50 years from now think about this?",
    },
    {
        "name": "Adversarial perspective",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for identifying vulnerabilities, weaknesses, and attack vectors from someone trying to break or exploit the concept.",
        "example": "If you were trying to find flaws in this, where would you look?",
    },
    {
        "name": "Optimist vs pessimist",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires presenting both the most hopeful and most concerning interpretations side by side.",
        "example": "Give me both the optimistic and pessimistic take on this.",
    },
    {
        "name": "Outsider looking in",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for the perspective of someone completely unfamiliar with the field observing it for the first time.",
        "example": "How would someone outside this field perceive this?",
    },
    {
        "name": "Stakeholder analysis",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires examining the topic from the viewpoints of multiple different affected parties.",
        "example": "How would each stakeholder group view this decision differently?",
    },
    {
        "name": "Contrarian view",
        "level": "complex",
        "ambiguity": "low",
        "description": "Demands articulating a position that goes against the mainstream or consensus understanding.",
        "example": "What's the contrarian take on this that most people miss?",
    },
    # =========================================================================
    # MULTI-STEP / COMPOUND
    # =========================================================================
    {
        "name": "Summarize then critique",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires first presenting a fair summary, then separately evaluating its strengths and weaknesses.",
        "example": "First summarize this approach, then give your critique.",
    },
    {
        "name": "Explain then give examples",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Asks for a general explanation followed by concrete illustrative examples.",
        "example": "Explain the concept, then give three concrete examples.",
    },
    {
        "name": "Define then apply",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Requires first providing a precise definition, then showing how it applies in a real scenario.",
        "example": "Define this term, then show how it applies in practice.",
    },
    {
        "name": "List then elaborate",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Asks for an initial brief list followed by detailed expansion on each item.",
        "example": "List the key factors, then elaborate on each one.",
    },
    {
        "name": "Describe then recommend",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires objectively describing a situation first, then providing actionable recommendations.",
        "example": "Describe the current state, then recommend next steps.",
    },
    {
        "name": "Analyze then synthesize",
        "level": "expert",
        "ambiguity": "low",
        "description": "Demands breaking something into its constituent parts and then recombining insights into a new unified understanding.",
        "example": "Analyze the individual components, then synthesize them into a cohesive view.",
    },
    {
        "name": "Compare then choose",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires a balanced comparison of options followed by a justified recommendation for one.",
        "example": "Compare the alternatives, then tell me which one you'd choose and why.",
    },
    {
        "name": "Diagnose then treat",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for first identifying the underlying problem, then proposing solutions to address it.",
        "example": "First diagnose what's going wrong, then suggest how to fix it.",
    },
    {
        "name": "Question then answer",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires first generating the right questions to ask, then answering each one systematically.",
        "example": "What questions should we be asking? Then answer each one.",
    },
    {
        "name": "Simplify then deepen",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for an initial simple overview followed by a deep, nuanced second pass.",
        "example": "Give me the simple version first, then go deeper with the nuances.",
    },
    {
        "name": "Brainstorm then filter",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires generating many ideas without judgment first, then critically evaluating and selecting the best ones.",
        "example": "Brainstorm 10 ideas, then narrow it down to the top 3 with reasoning.",
    },
    {
        "name": "Outline then draft",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for creating a structural outline first, then fleshing it out into full prose.",
        "example": "Create an outline first, then write the full version.",
    },
    {
        "name": "Identify then mitigate",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires first cataloging risks or issues, then proposing specific mitigation strategies for each.",
        "example": "Identify the risks, then propose a mitigation plan for each.",
    },
    {
        "name": "Hypothesize then test",
        "level": "expert",
        "ambiguity": "low",
        "description": "Demands forming a hypothesis first, then designing a way to validate or falsify it.",
        "example": "State your hypothesis, then describe how you'd test it.",
    },
    {
        "name": "Abstract then instantiate",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for stating a general principle, then providing specific concrete instances of it.",
        "example": "State the general rule, then give three specific instances.",
    },
    # =========================================================================
    # AMBIGUOUS / UNDERSPECIFIED
    # =========================================================================
    {
        "name": "Make it better",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Provides no criteria for improvement, requiring the responder to infer what 'better' means from context.",
        "example": "Make this better.",
    },
    {
        "name": "Fix this",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Implies something is broken without specifying what is wrong or what the desired outcome is.",
        "example": "Fix this.",
    },
    {
        "name": "Clean it up",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Suggests the current state is messy without defining what 'clean' means in context.",
        "example": "Clean this up.",
    },
    {
        "name": "What do you think?",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Asks for an opinion without specifying what aspect to evaluate or what criteria to use.",
        "example": "What do you think about this?",
    },
    {
        "name": "Tell me about it",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Provides an extremely open-ended prompt with no guidance on scope, depth, or focus area.",
        "example": "Tell me about this.",
    },
    {
        "name": "Help me with this",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Requests assistance without specifying what kind of help is needed or what the goal is.",
        "example": "Help me with this.",
    },
    {
        "name": "Make it more professional",
        "level": "ambiguous",
        "ambiguity": "moderate",
        "description": "Uses a subjective quality criterion that depends heavily on context and audience expectations.",
        "example": "Make this sound more professional.",
    },
    {
        "name": "Improve the flow",
        "level": "ambiguous",
        "ambiguity": "moderate",
        "description": "References an abstract quality of coherence and readability without specifying what disrupts it.",
        "example": "Improve the flow of this.",
    },
    {
        "name": "Make it pop",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Uses vague aesthetic language that could mean visual impact, excitement, clarity, or distinctiveness.",
        "example": "Make this pop more.",
    },
    {
        "name": "Something feels off",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Expresses unease without identifying the specific source, requiring diagnostic investigation.",
        "example": "Something feels off about this. Can you figure out what?",
    },
    {
        "name": "Make it shorter",
        "level": "ambiguous",
        "ambiguity": "moderate",
        "description": "Requests reduction without specifying how much shorter or what to cut, requiring editorial judgment.",
        "example": "This is too long. Make it shorter.",
    },
    {
        "name": "Make it longer",
        "level": "ambiguous",
        "ambiguity": "moderate",
        "description": "Requests expansion without specifying what to add or how much, risking padding without substance.",
        "example": "This needs to be longer. Expand it.",
    },
    {
        "name": "Do the usual",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "References an assumed shared understanding of routine procedures that may not exist.",
        "example": "Just do the usual thing here.",
    },
    {
        "name": "Make it work",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Implies something is non-functional without specifying the failure mode or success criteria.",
        "example": "This doesn't work. Make it work.",
    },
    {
        "name": "I don't like it",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Expresses dissatisfaction without articulating specific objections or desired changes.",
        "example": "I don't like this. Change it.",
    },
    {
        "name": "Needs more oomph",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Uses highly subjective language to request more impact, energy, or persuasiveness without defining the target.",
        "example": "This needs more oomph. Punch it up.",
    },
    {
        "name": "Polish it",
        "level": "ambiguous",
        "ambiguity": "moderate",
        "description": "Implies the content is nearly done but needs refinement without specifying which aspects.",
        "example": "This is almost there. Just polish it.",
    },
    {
        "name": "Make it interesting",
        "level": "ambiguous",
        "ambiguity": "high",
        "description": "Requests engagement without specifying what the audience finds interesting or how to achieve it.",
        "example": "This is boring. Make it interesting.",
    },
    # =========================================================================
    # META-INSTRUCTIONS
    # =========================================================================
    {
        "name": "Be concise",
        "level": "simple",
        "ambiguity": "moderate",
        "description": "Instructs brevity without specifying a precise length, relying on shared understanding of conciseness.",
        "example": "Be concise in your answer.",
    },
    {
        "name": "Be thorough",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requests comprehensive coverage without specifying boundaries, risking scope creep.",
        "example": "Be thorough. I want to understand every aspect.",
    },
    {
        "name": "Prioritize clarity",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Instructs that understandability should take precedence over precision, completeness, or elegance.",
        "example": "Prioritize clarity above everything else in your explanation.",
    },
    {
        "name": "Be specific",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for concrete details rather than generalities, but leaves the level of specificity open.",
        "example": "Be specific. I don't want generalities.",
    },
    {
        "name": "Be actionable",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires that every point lead to a clear next step the reader can take.",
        "example": "Make every recommendation actionable.",
    },
    {
        "name": "Be objective",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Instructs removing personal opinion and presenting only factual, evidence-based information.",
        "example": "Be completely objective. No opinions.",
    },
    {
        "name": "Be creative",
        "level": "moderate",
        "ambiguity": "high",
        "description": "Requests novelty and originality without specifying what creative means in context.",
        "example": "Be creative with your approach.",
    },
    {
        "name": "Be diplomatic",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for tactful, non-confrontational framing that considers the feelings of all parties.",
        "example": "Be diplomatic in how you phrase this feedback.",
    },
    {
        "name": "Be exhaustive",
        "level": "expert",
        "ambiguity": "moderate",
        "description": "Demands covering every possible aspect, edge case, and variation with nothing left out.",
        "example": "Be exhaustive. Leave nothing out.",
    },
    {
        "name": "Be practical",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Instructs focusing on real-world applicability rather than theoretical elegance.",
        "example": "Skip the theory. Be practical.",
    },
    {
        "name": "Be provocative",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for a response that challenges assumptions and stimulates strong reactions or debate.",
        "example": "Be provocative. Challenge my assumptions.",
    },
    {
        "name": "Be precise",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires exact, unambiguous language with no room for misinterpretation.",
        "example": "Be precise. Every word should be carefully chosen.",
    },
    {
        "name": "Be succinct",
        "level": "simple",
        "ambiguity": "low",
        "description": "Asks for the shortest possible response that still fully answers the question.",
        "example": "Be succinct. Give me the shortest possible answer.",
    },
    {
        "name": "Be balanced",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires giving equal weight to all sides of an issue without favoring any perspective.",
        "example": "Be balanced. Give equal weight to all perspectives.",
    },
    {
        "name": "Don't hold back",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requests blunt, unfiltered honesty regardless of how uncomfortable the truth may be.",
        "example": "Don't hold back. Give me your honest assessment.",
    },
    {
        "name": "Keep it simple",
        "level": "simple",
        "ambiguity": "low",
        "description": "Instructs avoiding complexity in both language and structure, favoring the most straightforward approach.",
        "example": "Keep it simple. No overcomplicating things.",
    },
    {
        "name": "Go deep",
        "level": "expert",
        "ambiguity": "moderate",
        "description": "Asks for an in-depth analysis that goes well beyond surface-level understanding.",
        "example": "Go deep on this. I want real depth, not surface-level.",
    },
    # =========================================================================
    # AUDIENCE-TARGETED
    # =========================================================================
    {
        "name": "For a non-technical audience",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires adapting content for people without specialized knowledge, avoiding all domain-specific terms.",
        "example": "Explain this for someone with no technical background.",
    },
    {
        "name": "For executives",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Demands a high-level, business-impact-focused summary appropriate for senior leadership.",
        "example": "Frame this for a C-level executive who has 2 minutes.",
    },
    {
        "name": "For a peer reviewer",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires the level of rigor and precision expected in formal expert-to-expert evaluation.",
        "example": "Write this at the level expected for peer review.",
    },
    {
        "name": "For a complete newcomer",
        "level": "simple",
        "ambiguity": "low",
        "description": "Targets someone with literally zero context, requiring building up from absolute basics.",
        "example": "Explain this for someone who has never encountered this field.",
    },
    {
        "name": "For an impatient reader",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires front-loading key information and making every word earn its place, as the reader may stop at any point.",
        "example": "Write this for someone who might stop reading after the first paragraph.",
    },
    {
        "name": "For a skeptical audience",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires anticipating objections and preemptively addressing doubts throughout the explanation.",
        "example": "Write this for an audience that will question every claim.",
    },
    {
        "name": "For a global audience",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Requires avoiding culture-specific references and assumptions to be universally understandable.",
        "example": "Make this understandable for a diverse, international audience.",
    },
    {
        "name": "For someone in a hurry",
        "level": "simple",
        "ambiguity": "low",
        "description": "Optimizes for speed of comprehension with scannable formatting and minimal reading time.",
        "example": "I'm in a hurry. Give me what I need to know fast.",
    },
    {
        "name": "For a visual learner",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for descriptions that emphasize spatial relationships, diagrams, and visual metaphors.",
        "example": "Explain this in a way that a visual learner would appreciate.",
    },
    # =========================================================================
    # ANALYTICAL / REASONING
    # =========================================================================
    {
        "name": "Steelman the argument",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires presenting the strongest possible version of an argument, even if the responder disagrees with it.",
        "example": "Steelman this position. Give me the strongest possible version.",
    },
    {
        "name": "Find the logical fallacies",
        "level": "expert",
        "ambiguity": "low",
        "description": "Demands identifying specific named reasoning errors and explaining why they undermine the argument.",
        "example": "What logical fallacies are present in this argument?",
    },
    {
        "name": "Second-order effects",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires thinking beyond immediate consequences to the indirect, downstream effects of an action.",
        "example": "What are the second-order effects of this decision?",
    },
    {
        "name": "Identify hidden assumptions",
        "level": "complex",
        "ambiguity": "low",
        "description": "Demands surfacing the unstated premises and taken-for-granted beliefs underlying a claim or plan.",
        "example": "What hidden assumptions does this argument rely on?",
    },
    {
        "name": "Thought experiment",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for exploring a hypothetical scenario to test the limits or implications of an idea.",
        "example": "Design a thought experiment to test this principle.",
    },
    {
        "name": "Inversion thinking",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires approaching a problem by thinking about what would cause failure rather than success.",
        "example": "Invert the problem. What would we need to do to guarantee failure?",
    },
    {
        "name": "Edge case analysis",
        "level": "expert",
        "ambiguity": "low",
        "description": "Demands identifying extreme or unusual scenarios where the normal rules or assumptions break down.",
        "example": "What are the edge cases that could break this approach?",
    },
    {
        "name": "Sensitivity analysis",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires examining how changes in input variables or assumptions affect the outcome.",
        "example": "Which assumptions, if wrong, would most change the conclusion?",
    },
    {
        "name": "Counterfactual reasoning",
        "level": "expert",
        "ambiguity": "moderate",
        "description": "Asks for exploring what would have happened under different conditions or decisions.",
        "example": "What would have happened if the opposite decision had been made?",
    },
    {
        "name": "Probabilistic assessment",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires assigning likelihoods and confidence levels rather than giving definitive yes/no answers.",
        "example": "Give me your probabilistic assessment with confidence levels.",
    },
    {
        "name": "Bayesian update",
        "level": "expert",
        "ambiguity": "low",
        "description": "Asks for adjusting beliefs based on new evidence using prior probability and likelihood reasoning.",
        "example": "Given this new information, how should I update my beliefs?",
    },
    {
        "name": "Pre-mortem analysis",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires imagining a project has failed and working backward to identify what likely caused the failure.",
        "example": "Imagine this plan has failed. What went wrong?",
    },
    {
        "name": "Opportunity cost framing",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for evaluating a choice not just on its merits but on what is given up by not choosing alternatives.",
        "example": "What's the opportunity cost of going with this approach?",
    },
    {
        "name": "Fermi estimation",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires making reasonable order-of-magnitude estimates using logical decomposition and limited data.",
        "example": "Give me a Fermi estimate for this quantity.",
    },
    {
        "name": "Systems thinking",
        "level": "expert",
        "ambiguity": "moderate",
        "description": "Demands analyzing how components interact within a larger system, including feedback loops and emergent behaviors.",
        "example": "Analyze this using systems thinking. What are the feedback loops?",
    },
    {
        "name": "Red team this",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires adversarially attacking a plan or argument to find its weaknesses before real opponents do.",
        "example": "Red team this plan. Try to tear it apart.",
    },
    # =========================================================================
    # CREATIVE / GENERATIVE
    # =========================================================================
    {
        "name": "Brainstorm",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for generating many diverse ideas without filtering or judging them initially.",
        "example": "Brainstorm 20 different approaches to this problem.",
    },
    {
        "name": "What-if scenario",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires exploring hypothetical variations by changing one or more key variables.",
        "example": "What if we had twice the budget but half the time?",
    },
    {
        "name": "Random combination",
        "level": "complex",
        "ambiguity": "high",
        "description": "Asks for combining seemingly unrelated concepts to generate novel ideas or solutions.",
        "example": "Combine two unrelated ideas to create something new.",
    },
    {
        "name": "Worst possible version",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for deliberately creating the worst version to reveal pitfalls and generate insight through inversion.",
        "example": "What would the worst possible version of this look like?",
    },
    {
        "name": "Constrained creativity",
        "level": "complex",
        "ambiguity": "low",
        "description": "Imposes artificial constraints to force novel solutions that wouldn't emerge under normal conditions.",
        "example": "Solve this problem, but you can only use resources that already exist.",
    },
    {
        "name": "Lateral thinking",
        "level": "complex",
        "ambiguity": "high",
        "description": "Asks for approaching a problem from an unexpected angle rather than the obvious logical path.",
        "example": "Approach this problem from a completely unexpected angle.",
    },
    {
        "name": "SCAMPER method",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires systematically applying Substitute, Combine, Adapt, Modify, Put to other uses, Eliminate, Reverse.",
        "example": "Apply the SCAMPER method to improve this concept.",
    },
    {
        "name": "Reverse brainstorm",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for brainstorming ways to cause the problem rather than solve it, then inverting each idea.",
        "example": "How could we make this problem worse? Now invert each idea into a solution.",
    },
    # =========================================================================
    # EVALUATION / JUDGMENT
    # =========================================================================
    {
        "name": "Rate on a scale",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for a numerical or ordinal assessment with justification for the rating.",
        "example": "Rate this approach on a scale of 1-10 and explain your rating.",
    },
    {
        "name": "Verdict with reasoning",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires a clear conclusion supported by explicit reasoning that led to that judgment.",
        "example": "Give me your verdict and walk me through your reasoning.",
    },
    {
        "name": "Cost-benefit analysis",
        "level": "complex",
        "ambiguity": "low",
        "description": "Demands a systematic weighing of costs against benefits with an overall assessment.",
        "example": "Do a cost-benefit analysis of this proposal.",
    },
    {
        "name": "Feasibility assessment",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires evaluating whether something is practically achievable given real-world constraints.",
        "example": "Assess whether this plan is actually feasible.",
    },
    {
        "name": "Risk assessment",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for identifying potential risks, rating their probability and impact, and suggesting mitigations.",
        "example": "What are the risks, and how severe is each one?",
    },
    {
        "name": "Grade the argument",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires evaluating the quality of reasoning, evidence, and persuasiveness of an argument.",
        "example": "Grade this argument. How strong is the reasoning?",
    },
    {
        "name": "Confidence calibration",
        "level": "expert",
        "ambiguity": "low",
        "description": "Asks for explicit statements about what the responder is and isn't confident about.",
        "example": "How confident are you in each part of your answer?",
    },
    {
        "name": "Trade-off analysis",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires identifying what is gained and lost with each option in a decision.",
        "example": "What are the trade-offs between these two approaches?",
    },
    # =========================================================================
    # COMMUNICATION STYLES
    # =========================================================================
    {
        "name": "As a FAQ",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires anticipating common questions and organizing information in question-answer format.",
        "example": "Present this information as a FAQ with the most likely questions.",
    },
    {
        "name": "As a memo",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for formal business memo format with headers, key points, and recommendations.",
        "example": "Write this up as a brief memo.",
    },
    {
        "name": "As talking points",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires distilling information into brief, speakable points for verbal delivery.",
        "example": "Give me talking points I can use in a meeting.",
    },
    {
        "name": "As a checklist",
        "level": "simple",
        "ambiguity": "none",
        "description": "Asks for converting information into a sequential list of verifiable action items.",
        "example": "Turn this into a checklist I can follow.",
    },
    {
        "name": "As a tutorial",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires a hands-on, follow-along instructional format with clear progression from start to finish.",
        "example": "Write this as a step-by-step tutorial.",
    },
    {
        "name": "As a reference card",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for a dense, scannable quick-reference format optimized for lookup rather than learning.",
        "example": "Create a reference card I can pin to my wall.",
    },
    {
        "name": "As a decision guide",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires structuring information as a guide that helps someone make a specific decision.",
        "example": "Write this as a decision guide with clear criteria.",
    },
    {
        "name": "As an executive summary",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for a condensed overview highlighting key findings, conclusions, and recommendations for senior leadership.",
        "example": "Write an executive summary of this analysis.",
    },
    {
        "name": "As a verbal explanation",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for writing as if speaking aloud, with a conversational tone and natural flow.",
        "example": "Explain this as if you're talking to me in person.",
    },
    {
        "name": "As a debate brief",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires structuring arguments for both sides with evidence and rebuttals in formal debate format.",
        "example": "Prepare a debate brief covering both sides of this issue.",
    },
    # =========================================================================
    # SCOPE / DEPTH MODIFIERS
    # =========================================================================
    {
        "name": "Big picture only",
        "level": "simple",
        "ambiguity": "moderate",
        "description": "Asks for the highest-level overview without any granular detail, focusing on overarching themes.",
        "example": "Just give me the big picture. No details.",
    },
    {
        "name": "Deep dive",
        "level": "expert",
        "ambiguity": "moderate",
        "description": "Requires an intensive, detailed exploration of a topic going far beyond surface understanding.",
        "example": "Do a deep dive into this topic.",
    },
    {
        "name": "Surface-level scan",
        "level": "simple",
        "ambiguity": "low",
        "description": "Asks for a quick, high-level pass without going into any depth on any point.",
        "example": "Just give me a surface-level scan of the key points.",
    },
    {
        "name": "Comprehensive review",
        "level": "expert",
        "ambiguity": "low",
        "description": "Demands covering all aspects systematically with no gaps in the analysis.",
        "example": "Give me a comprehensive review that leaves no stone unturned.",
    },
    {
        "name": "Focus on the exceptions",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for ignoring the typical cases and concentrating on unusual, atypical, or edge scenarios.",
        "example": "Skip the normal cases. What are the exceptions?",
    },
    {
        "name": "Just the facts",
        "level": "simple",
        "ambiguity": "low",
        "description": "Requests only verifiable factual information stripped of interpretation, opinion, or analysis.",
        "example": "Just the facts. No commentary.",
    },
    {
        "name": "Only what changed",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for focusing exclusively on deltas and differences from a known baseline state.",
        "example": "I know the old version. Just tell me what changed.",
    },
    {
        "name": "Zoom in on one aspect",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Requires selecting and deeply exploring one specific facet while ignoring everything else.",
        "example": "Zoom in on just the most critical aspect of this.",
    },
    {
        "name": "Breadth over depth",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for covering many topics lightly rather than going deep on any single one.",
        "example": "Give me broad coverage. Touch on everything but don't go deep.",
    },
    {
        "name": "Depth over breadth",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for intensive focus on fewer topics rather than shallow coverage of many.",
        "example": "Pick the most important point and go really deep on it.",
    },
    # =========================================================================
    # TEMPORAL / PROCESS
    # =========================================================================
    {
        "name": "Phased plan",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires breaking an initiative into distinct temporal phases with clear milestones and transitions.",
        "example": "Break this into phases with clear milestones.",
    },
    {
        "name": "Quick wins first",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for prioritizing items by ease and speed of implementation, starting with the simplest.",
        "example": "Start with the quick wins and work up to the harder items.",
    },
    {
        "name": "Dependency order",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires sequencing tasks based on their prerequisites and interdependencies.",
        "example": "Put these in order based on what depends on what.",
    },
    {
        "name": "Parallel tracks",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for identifying which activities can proceed simultaneously and organizing them as parallel workstreams.",
        "example": "Which of these can happen in parallel, and which must be sequential?",
    },
    {
        "name": "MVP first",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires identifying the minimum viable version that delivers core value before expanding scope.",
        "example": "What's the minimum viable version of this? Start there.",
    },
    {
        "name": "Iterative refinement plan",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for a plan that starts rough and improves through multiple cycles of feedback and revision.",
        "example": "Design this as an iterative process with multiple refinement cycles.",
    },
    # =========================================================================
    # CONTRADICTORY / PARADOXICAL
    # =========================================================================
    {
        "name": "Be brief but thorough",
        "level": "complex",
        "ambiguity": "contradictory",
        "description": "Contains inherently conflicting requirements between brevity and completeness, requiring careful balance.",
        "example": "Be brief but don't leave anything important out.",
    },
    {
        "name": "Simple but not simplistic",
        "level": "complex",
        "ambiguity": "contradictory",
        "description": "Demands accessible presentation without dumbing down the content, a nuanced balancing act.",
        "example": "Make it simple but don't oversimplify.",
    },
    {
        "name": "Be creative but realistic",
        "level": "complex",
        "ambiguity": "contradictory",
        "description": "Asks for novel ideas that are also grounded and practically implementable, constraining both imagination and pragmatism.",
        "example": "I want creative ideas, but they need to be realistic.",
    },
    {
        "name": "Be bold but safe",
        "level": "complex",
        "ambiguity": "contradictory",
        "description": "Contains tension between risk-taking and risk-avoidance, requiring calibration of how far to push.",
        "example": "Be bold in your recommendations but keep the risk low.",
    },
    {
        "name": "Detailed overview",
        "level": "complex",
        "ambiguity": "contradictory",
        "description": "Paradoxically requests both high-level summary and granular detail simultaneously.",
        "example": "Give me a detailed overview.",
    },
    {
        "name": "Quick but careful",
        "level": "moderate",
        "ambiguity": "contradictory",
        "description": "Asks for speed and thoroughness simultaneously, requiring judgment about which corners can be cut.",
        "example": "Do this quickly but don't rush it.",
    },
    {
        "name": "Everything but keep it short",
        "level": "complex",
        "ambiguity": "contradictory",
        "description": "Demands comprehensive coverage within a tight space constraint, requiring extreme prioritization skills.",
        "example": "Cover everything, but keep it to one page.",
    },
    {
        "name": "Be original but follow the template",
        "level": "moderate",
        "ambiguity": "contradictory",
        "description": "Asks for novelty within a rigid structural constraint, limiting the dimensions in which creativity can operate.",
        "example": "Be original, but stick to the standard format.",
    },
    {
        "name": "Be specific but keep options open",
        "level": "complex",
        "ambiguity": "contradictory",
        "description": "Requires concrete detail while maintaining flexibility, a tension between commitment and optionality.",
        "example": "Be specific in your recommendation but don't lock us in.",
    },
    {
        "name": "Technical but accessible",
        "level": "complex",
        "ambiguity": "contradictory",
        "description": "Demands accurate technical detail that is simultaneously understandable by non-experts.",
        "example": "Make it technically accurate but accessible to a general audience.",
    },
    # =========================================================================
    # REASONING CHAIN TYPES
    # =========================================================================
    {
        "name": "Deductive reasoning",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires starting from general premises and logically deriving specific conclusions through valid inference.",
        "example": "Use deductive reasoning to arrive at the conclusion.",
    },
    {
        "name": "Inductive reasoning",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for building a general principle from specific observations and examples.",
        "example": "Based on these examples, what general rule can you induce?",
    },
    {
        "name": "Abductive reasoning",
        "level": "expert",
        "ambiguity": "moderate",
        "description": "Requires inferring the most likely explanation given incomplete evidence.",
        "example": "Given the evidence, what's the best explanation?",
    },
    {
        "name": "Analogical reasoning",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for drawing conclusions about one domain based on similarities with another known domain.",
        "example": "What can we learn from a similar situation in a different context?",
    },
    {
        "name": "Chain of thought",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires showing each step of the reasoning process explicitly, making the logic chain visible.",
        "example": "Walk me through your chain of thought.",
    },
    {
        "name": "Show your work",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Demands that the reasoning process be made fully transparent, not just the final answer.",
        "example": "Show your work. I want to see how you got there.",
    },
    # =========================================================================
    # TRANSFORMATION / CONVERSION
    # =========================================================================
    {
        "name": "Translate to layperson terms",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires converting specialized language into everyday vocabulary while preserving meaning.",
        "example": "Translate this jargon into language anyone could understand.",
    },
    {
        "name": "Formalize informal content",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for converting casual or colloquial content into formal, professional language.",
        "example": "Take this casual description and make it formal.",
    },
    {
        "name": "Convert to action items",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires transforming descriptive text into specific, assignable tasks with clear completion criteria.",
        "example": "Convert this discussion into a list of clear action items.",
    },
    {
        "name": "Narrative to data",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for extracting structured data points from unstructured narrative text.",
        "example": "Pull out the key data points from this narrative.",
    },
    {
        "name": "Data to narrative",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires weaving raw data points into a coherent, readable story or explanation.",
        "example": "Turn these data points into a coherent narrative.",
    },
    {
        "name": "Condense without losing nuance",
        "level": "expert",
        "ambiguity": "low",
        "description": "Demands significant compression while preserving subtle distinctions and qualifications in the original.",
        "example": "Make this half the length without losing any nuance.",
    },
    {
        "name": "Expand with substance",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires adding meaningful depth and detail rather than just padding with filler words.",
        "example": "This needs more substance. Expand it meaningfully.",
    },
    {
        "name": "Reframe positively",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for restating negative findings or problems in terms of opportunities and constructive next steps.",
        "example": "Reframe these problems as opportunities.",
    },
    {
        "name": "Reframe negatively",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for restating positive claims in terms of risks, costs, and potential downsides.",
        "example": "Now give me the pessimistic reframe of these benefits.",
    },
    # =========================================================================
    # VERIFICATION / QUALITY
    # =========================================================================
    {
        "name": "Fact-check this",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires verifying each claim against known facts and flagging anything unsubstantiated or incorrect.",
        "example": "Fact-check each claim in this passage.",
    },
    {
        "name": "Sanity check",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for a quick reasonableness assessment to catch obvious errors or unrealistic elements.",
        "example": "Do a sanity check. Does this make sense?",
    },
    {
        "name": "Stress test",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires pushing a plan or idea to its limits to find where it breaks under extreme conditions.",
        "example": "Stress test this plan. What breaks under pressure?",
    },
    {
        "name": "Peer review simulation",
        "level": "expert",
        "ambiguity": "low",
        "description": "Asks for rigorous evaluation as if formally reviewing someone's work for accuracy and completeness.",
        "example": "Review this as if you were a peer reviewer looking for flaws.",
    },
    {
        "name": "Find the weakest link",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires identifying the single most vulnerable point in a chain of reasoning or plan.",
        "example": "What's the weakest link in this argument?",
    },
    {
        "name": "Verify the logic",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for checking whether each logical step follows from the previous one without gaps or errors.",
        "example": "Check whether the logic holds at every step.",
    },
    {
        "name": "Challenge every assumption",
        "level": "expert",
        "ambiguity": "low",
        "description": "Demands questioning every stated and unstated assumption to test the robustness of the conclusion.",
        "example": "Challenge every assumption in this analysis.",
    },
    # =========================================================================
    # SPECIFICITY LEVELS
    # =========================================================================
    {
        "name": "Give me the gist",
        "level": "simple",
        "ambiguity": "low",
        "description": "Asks for the essential meaning without precision or detail, just the general idea.",
        "example": "Just give me the gist of this.",
    },
    {
        "name": "With exact numbers",
        "level": "complex",
        "ambiguity": "none",
        "description": "Demands precise quantitative data rather than vague qualifiers like 'many' or 'significant'.",
        "example": "Give me exact numbers, not approximations.",
    },
    {
        "name": "With citations",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires attributing claims to specific sources with enough detail to verify them.",
        "example": "Support each claim with a specific citation.",
    },
    {
        "name": "With concrete examples",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Asks for tangible, specific instances rather than abstract descriptions.",
        "example": "Don't just tell me the theory. Give me concrete examples.",
    },
    {
        "name": "With caveats noted",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires explicitly acknowledging limitations, exceptions, and conditions under which claims hold.",
        "example": "Include all the important caveats and limitations.",
    },
    {
        "name": "With confidence intervals",
        "level": "expert",
        "ambiguity": "low",
        "description": "Demands expressing uncertainty ranges around estimates rather than giving single point values.",
        "example": "Give me your estimates with confidence intervals.",
    },
    {
        "name": "With alternatives noted",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires flagging other possible interpretations or approaches alongside the primary recommendation.",
        "example": "For each point, also mention what alternatives exist.",
    },
    # =========================================================================
    # TONE / REGISTER
    # =========================================================================
    {
        "name": "Formal register",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires using professional, academic, or official language with proper conventions.",
        "example": "Write this in a formal, professional tone.",
    },
    {
        "name": "Conversational tone",
        "level": "simple",
        "ambiguity": "low",
        "description": "Asks for a relaxed, friendly writing style as if chatting with a colleague.",
        "example": "Keep it conversational. Like you're talking to a friend.",
    },
    {
        "name": "No-nonsense direct",
        "level": "simple",
        "ambiguity": "low",
        "description": "Requires cutting all pleasantries and hedging to deliver information as directly as possible.",
        "example": "Cut the fluff. Be direct.",
    },
    {
        "name": "Empathetic framing",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for acknowledging emotional dimensions and framing information with sensitivity.",
        "example": "Frame this with empathy. This is a sensitive topic.",
    },
    {
        "name": "Authoritative voice",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires projecting confidence and expertise through definitive language and strong assertions.",
        "example": "Write this with authority. Sound like you're the definitive source.",
    },
    {
        "name": "Humorous approach",
        "level": "moderate",
        "ambiguity": "high",
        "description": "Asks for incorporating humor while still conveying accurate information, a tricky balance.",
        "example": "Explain this in a funny way, but keep it accurate.",
    },
    {
        "name": "Neutral reporting",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires a detached, journalist-like presentation of facts without editorial comment.",
        "example": "Report on this neutrally, like a news article.",
    },
    {
        "name": "Cautionary tone",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for emphasizing risks, warnings, and potential pitfalls throughout the explanation.",
        "example": "Frame this as a cautionary guide. Emphasize what could go wrong.",
    },
    # =========================================================================
    # SYNTHESIS / INTEGRATION
    # =========================================================================
    {
        "name": "Connect the dots",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for finding non-obvious relationships and patterns among seemingly unrelated pieces of information.",
        "example": "Connect the dots between these seemingly unrelated facts.",
    },
    {
        "name": "Find the common thread",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires identifying the unifying theme or principle that ties multiple disparate items together.",
        "example": "What's the common thread linking all of these?",
    },
    {
        "name": "Reconcile contradictions",
        "level": "expert",
        "ambiguity": "low",
        "description": "Demands finding a framework that explains how seemingly contradictory facts can both be true.",
        "example": "These two facts seem contradictory. How do you reconcile them?",
    },
    {
        "name": "Cross-domain synthesis",
        "level": "expert",
        "ambiguity": "moderate",
        "description": "Requires combining insights from different fields into a unified understanding that transcends each individual domain.",
        "example": "What can we learn by combining insights from these different fields?",
    },
    {
        "name": "Meta-analysis style",
        "level": "expert",
        "ambiguity": "low",
        "description": "Asks for aggregating findings across multiple sources or instances to draw higher-level conclusions.",
        "example": "Look across all of these and tell me what the aggregate pattern is.",
    },
    {
        "name": "Distill the principle",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires extracting the underlying general principle from specific examples or cases.",
        "example": "What's the underlying principle that explains all of these cases?",
    },
    {
        "name": "Build a unified framework",
        "level": "expert",
        "ambiguity": "moderate",
        "description": "Demands creating a single coherent model that organizes multiple concepts into a structured whole.",
        "example": "Can you build a framework that ties all these concepts together?",
    },
    # =========================================================================
    # BOUNDARY / SCOPE SETTING
    # =========================================================================
    {
        "name": "What's in scope vs out of scope",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires explicitly defining what is and isn't included in the discussion or analysis.",
        "example": "Define clearly what's in scope and what's out of scope.",
    },
    {
        "name": "Where to draw the line",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for identifying the appropriate boundaries or thresholds for a given context.",
        "example": "Where should we draw the line on this?",
    },
    {
        "name": "When to stop",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires defining clear stopping criteria or diminishing returns thresholds for a process.",
        "example": "How do we know when we've done enough?",
    },
    {
        "name": "Must-have vs nice-to-have",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for categorizing items into essential requirements versus optional enhancements.",
        "example": "Separate the must-haves from the nice-to-haves.",
    },
    {
        "name": "80/20 analysis",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires identifying the 20% of factors that drive 80% of the results using Pareto principle reasoning.",
        "example": "Apply the 80/20 rule. What are the vital few that matter most?",
    },
    {
        "name": "Non-negotiables",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for identifying absolute requirements that cannot be compromised under any circumstances.",
        "example": "What are the non-negotiable requirements here?",
    },
    # =========================================================================
    # MISCELLANEOUS INSTRUCTION PATTERNS
    # =========================================================================
    {
        "name": "What would you do?",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for a personal recommendation or decision, requiring the responder to commit to a position.",
        "example": "If you were in my position, what would you do?",
    },
    {
        "name": "Predict the outcome",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires forecasting likely results based on current information and trends.",
        "example": "Based on what you know, predict how this will play out.",
    },
    {
        "name": "Rubber duck debug",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks the responder to listen to an explanation and find where the reasoning goes wrong.",
        "example": "Let me explain my thinking. Tell me where I go off track.",
    },
    {
        "name": "Steel vs straw",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires presenting both the strongest and weakest versions of an argument side by side for comparison.",
        "example": "Give me both the steelman and strawman versions of this argument.",
    },
    {
        "name": "Name the pattern",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for recognizing and labeling the underlying pattern or archetype in a situation.",
        "example": "What pattern or archetype is this an example of?",
    },
    {
        "name": "Fill in the gaps",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Requires identifying what information is missing and supplying or requesting it.",
        "example": "What's missing from this picture? Fill in the gaps.",
    },
    {
        "name": "Assume the worst",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires planning for the worst-case scenario and working backward from catastrophic failure.",
        "example": "Assume the worst case. What should we prepare for?",
    },
    {
        "name": "Assume the best",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Requires planning for the optimistic scenario and identifying what to do if everything goes right.",
        "example": "Assume everything goes perfectly. What should we be ready for?",
    },
    {
        "name": "Disagree with me",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Explicitly asks the responder to find and articulate points of disagreement.",
        "example": "Disagree with me. Where am I wrong?",
    },
    {
        "name": "Solve it backwards",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires working from the desired end state backward to determine what steps are needed.",
        "example": "Start from the end goal and work backwards to figure out the steps.",
    },
    {
        "name": "Map the landscape",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for a comprehensive survey of the space showing major players, positions, or categories.",
        "example": "Map out the entire landscape of approaches in this space.",
    },
    {
        "name": "Give me the gotchas",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks specifically for non-obvious traps, pitfalls, and surprises that commonly catch people off guard.",
        "example": "What are the gotchas that people commonly miss?",
    },
    {
        "name": "Bottom line up front",
        "level": "moderate",
        "ambiguity": "none",
        "description": "Requires stating the conclusion or recommendation first, then providing supporting reasoning afterward.",
        "example": "Bottom line up front. Then give me the supporting details.",
    },
    {
        "name": "If-then scenarios",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires mapping out conditional outcomes for different possible situations or decisions.",
        "example": "Give me if-then scenarios for each possible decision.",
    },
    {
        "name": "What am I missing?",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for identifying blind spots and overlooked factors in the questioner's current understanding.",
        "example": "Based on what I've said, what am I missing?",
    },
    {
        "name": "Teach me to fish",
        "level": "complex",
        "ambiguity": "moderate",
        "description": "Asks for teaching the underlying method rather than just providing the answer.",
        "example": "Don't just give me the answer. Teach me how to figure it out myself.",
    },
    {
        "name": "Give me the answer directly",
        "level": "simple",
        "ambiguity": "none",
        "description": "Explicitly requests just the final answer without explanation, reasoning, or caveats.",
        "example": "Just give me the answer. No explanation needed.",
    },
    {
        "name": "Walk before we run",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for starting with the simplest possible version before tackling complexity.",
        "example": "Let's walk before we run. What's the simplest version of this?",
    },
    {
        "name": "One thing at a time",
        "level": "simple",
        "ambiguity": "low",
        "description": "Requires focusing on a single element and completing it before moving to the next.",
        "example": "One thing at a time. What's the first thing I should focus on?",
    },
    {
        "name": "Most important thing",
        "level": "moderate",
        "ambiguity": "moderate",
        "description": "Asks for identifying the single highest-priority item among many competing options.",
        "example": "If I can only focus on one thing, what should it be?",
    },
    {
        "name": "Explain the tradeoff",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires articulating what is sacrificed to gain something else in a given decision.",
        "example": "What's the fundamental tradeoff at the heart of this decision?",
    },
    {
        "name": "Version for each audience",
        "level": "expert",
        "ambiguity": "low",
        "description": "Requires producing multiple versions of the same content tailored to different audience levels.",
        "example": "Give me three versions: one for beginners, one for practitioners, one for experts.",
    },
    {
        "name": "Eliminate options",
        "level": "moderate",
        "ambiguity": "low",
        "description": "Asks for systematically ruling out inferior options until only the best remain.",
        "example": "Help me eliminate the worst options to narrow my choice.",
    },
    {
        "name": "Label the unknowns",
        "level": "complex",
        "ambiguity": "low",
        "description": "Requires explicitly identifying and categorizing what is not known or uncertain in the current understanding.",
        "example": "What are the known unknowns here? And what might be unknown unknowns?",
    },
    {
        "name": "Benchmark comparison",
        "level": "complex",
        "ambiguity": "low",
        "description": "Asks for evaluating performance or quality against established standards or comparable references.",
        "example": "How does this compare against the standard benchmark?",
    },
]
